// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: api/zebra-config/file/file.proto
package file

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// FileServiceName is the fully-qualified name of the FileService service.
	FileServiceName = "file.FileService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FileServiceUploadProcedure is the fully-qualified name of the FileService's Upload RPC.
	FileServiceUploadProcedure = "/file.FileService/Upload"
)

var (
	_ FileService = (*FileServiceImpl)(nil)
)

// FileService is a client for the file.FileService service.
type FileService interface {
	Upload(ctx context.Context, req *UploadFileRequest, opts ...client.CallOption) (*UploadFileResponse, error)
}

// NewFileService constructs a client for the file.FileService service.
func NewFileService(cli *client.Client, opts ...client.ReferenceOption) (FileService, error) {
	conn, err := cli.DialWithInfo("file.FileService", &FileService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &FileServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerFileService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &FileService_ClientInfo)
}

// FileServiceImpl implements FileService.
type FileServiceImpl struct {
	conn *client.Connection
}

func (c *FileServiceImpl) Upload(ctx context.Context, req *UploadFileRequest, opts ...client.CallOption) (*UploadFileResponse, error) {
	resp := new(UploadFileResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "Upload", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var FileService_ClientInfo = client.ClientInfo{
	InterfaceName: "file.FileService",
	MethodNames:   []string{"Upload"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*FileServiceImpl)
		dubboCli.conn = conn
	},
}

// FileServiceHandler is an implementation of the file.FileService service.
type FileServiceHandler interface {
	Upload(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
}

func RegisterFileServiceHandler(srv *server.Server, hdlr FileServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &FileService_ServiceInfo, opts...)
}

func SetProviderFileService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &FileService_ServiceInfo)
}

var FileService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "file.FileService",
	ServiceType:   (*FileServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "Upload",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(UploadFileRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*UploadFileRequest)
				res, err := handler.(FileServiceHandler).Upload(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
