// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: api/zebra-passport/dept/dept.proto
package dept

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// DeptServiceName is the fully-qualified name of the DeptService service.
	DeptServiceName = "dept.DeptService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DeptServiceListProcedure is the fully-qualified name of the DeptService's List RPC.
	DeptServiceListProcedure = "/dept.DeptService/List"
	// DeptServiceListExcludeChildProcedure is the fully-qualified name of the DeptService's ListExcludeChild RPC.
	DeptServiceListExcludeChildProcedure = "/dept.DeptService/ListExcludeChild"
	// DeptServiceGetProcedure is the fully-qualified name of the DeptService's Get RPC.
	DeptServiceGetProcedure = "/dept.DeptService/Get"
	// DeptServiceCreateProcedure is the fully-qualified name of the DeptService's Create RPC.
	DeptServiceCreateProcedure = "/dept.DeptService/Create"
	// DeptServiceUpdateProcedure is the fully-qualified name of the DeptService's Update RPC.
	DeptServiceUpdateProcedure = "/dept.DeptService/Update"
	// DeptServiceUpdateSortProcedure is the fully-qualified name of the DeptService's UpdateSort RPC.
	DeptServiceUpdateSortProcedure = "/dept.DeptService/UpdateSort"
	// DeptServiceDeleteProcedure is the fully-qualified name of the DeptService's Delete RPC.
	DeptServiceDeleteProcedure = "/dept.DeptService/Delete"
)

var (
	_ DeptService = (*DeptServiceImpl)(nil)
)

// DeptService is a client for the dept.DeptService service.
type DeptService interface {
	List(ctx context.Context, req *ListDeptRequest, opts ...client.CallOption) (*ListDeptResponse, error)
	ListExcludeChild(ctx context.Context, req *ListDeptExcludeChildRequest, opts ...client.CallOption) (*ListDeptResponse, error)
	Get(ctx context.Context, req *GetDeptRequest, opts ...client.CallOption) (*GetDeptResponse, error)
	Create(ctx context.Context, req *CreateDeptRequest, opts ...client.CallOption) (*Response, error)
	Update(ctx context.Context, req *UpdateDeptRequest, opts ...client.CallOption) (*Response, error)
	UpdateSort(ctx context.Context, req *UpdateDeptSortRequest, opts ...client.CallOption) (*Response, error)
	Delete(ctx context.Context, req *DeleteDeptRequest, opts ...client.CallOption) (*Response, error)
}

// NewDeptService constructs a client for the dept.DeptService service.
func NewDeptService(cli *client.Client, opts ...client.ReferenceOption) (DeptService, error) {
	conn, err := cli.DialWithInfo("dept.DeptService", &DeptService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &DeptServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerDeptService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &DeptService_ClientInfo)
}

// DeptServiceImpl implements DeptService.
type DeptServiceImpl struct {
	conn *client.Connection
}

func (c *DeptServiceImpl) List(ctx context.Context, req *ListDeptRequest, opts ...client.CallOption) (*ListDeptResponse, error) {
	resp := new(ListDeptResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "List", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *DeptServiceImpl) ListExcludeChild(ctx context.Context, req *ListDeptExcludeChildRequest, opts ...client.CallOption) (*ListDeptResponse, error) {
	resp := new(ListDeptResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "ListExcludeChild", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *DeptServiceImpl) Get(ctx context.Context, req *GetDeptRequest, opts ...client.CallOption) (*GetDeptResponse, error) {
	resp := new(GetDeptResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "Get", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *DeptServiceImpl) Create(ctx context.Context, req *CreateDeptRequest, opts ...client.CallOption) (*Response, error) {
	resp := new(Response)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "Create", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *DeptServiceImpl) Update(ctx context.Context, req *UpdateDeptRequest, opts ...client.CallOption) (*Response, error) {
	resp := new(Response)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "Update", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *DeptServiceImpl) UpdateSort(ctx context.Context, req *UpdateDeptSortRequest, opts ...client.CallOption) (*Response, error) {
	resp := new(Response)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "UpdateSort", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *DeptServiceImpl) Delete(ctx context.Context, req *DeleteDeptRequest, opts ...client.CallOption) (*Response, error) {
	resp := new(Response)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "Delete", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var DeptService_ClientInfo = client.ClientInfo{
	InterfaceName: "dept.DeptService",
	MethodNames:   []string{"List", "ListExcludeChild", "Get", "Create", "Update", "UpdateSort", "Delete"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*DeptServiceImpl)
		dubboCli.conn = conn
	},
}

// DeptServiceHandler is an implementation of the dept.DeptService service.
type DeptServiceHandler interface {
	List(context.Context, *ListDeptRequest) (*ListDeptResponse, error)
	ListExcludeChild(context.Context, *ListDeptExcludeChildRequest) (*ListDeptResponse, error)
	Get(context.Context, *GetDeptRequest) (*GetDeptResponse, error)
	Create(context.Context, *CreateDeptRequest) (*Response, error)
	Update(context.Context, *UpdateDeptRequest) (*Response, error)
	UpdateSort(context.Context, *UpdateDeptSortRequest) (*Response, error)
	Delete(context.Context, *DeleteDeptRequest) (*Response, error)
}

func RegisterDeptServiceHandler(srv *server.Server, hdlr DeptServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &DeptService_ServiceInfo, opts...)
}

func SetProviderDeptService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &DeptService_ServiceInfo)
}

var DeptService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "dept.DeptService",
	ServiceType:   (*DeptServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "List",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(ListDeptRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*ListDeptRequest)
				res, err := handler.(DeptServiceHandler).List(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "ListExcludeChild",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(ListDeptExcludeChildRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*ListDeptExcludeChildRequest)
				res, err := handler.(DeptServiceHandler).ListExcludeChild(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "Get",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetDeptRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetDeptRequest)
				res, err := handler.(DeptServiceHandler).Get(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "Create",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(CreateDeptRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*CreateDeptRequest)
				res, err := handler.(DeptServiceHandler).Create(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "Update",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(UpdateDeptRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*UpdateDeptRequest)
				res, err := handler.(DeptServiceHandler).Update(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "UpdateSort",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(UpdateDeptSortRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*UpdateDeptSortRequest)
				res, err := handler.(DeptServiceHandler).UpdateSort(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "Delete",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(DeleteDeptRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*DeleteDeptRequest)
				res, err := handler.(DeptServiceHandler).Delete(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
