// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/zebra-passport/permission/permission.proto

package permission

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 权限检查请求
type HasPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Perms         string                 `protobuf:"bytes,2,opt,name=perms,proto3" json:"perms,omitempty"` // 权限标识，如 system:user:list
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPermissionRequest) Reset() {
	*x = HasPermissionRequest{}
	mi := &file_api_zebra_passport_permission_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionRequest) ProtoMessage() {}

func (x *HasPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_permission_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionRequest.ProtoReflect.Descriptor instead.
func (*HasPermissionRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_permission_permission_proto_rawDescGZIP(), []int{0}
}

func (x *HasPermissionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *HasPermissionRequest) GetPerms() string {
	if x != nil {
		return x.Perms
	}
	return ""
}

// 权限检查响应
type HasPermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码: 0=成功, -1=失败, -2=数据为空
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	HasPermission bool                   `protobuf:"varint,3,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPermissionResponse) Reset() {
	*x = HasPermissionResponse{}
	mi := &file_api_zebra_passport_permission_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionResponse) ProtoMessage() {}

func (x *HasPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_permission_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionResponse.ProtoReflect.Descriptor instead.
func (*HasPermissionResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_permission_permission_proto_rawDescGZIP(), []int{1}
}

func (x *HasPermissionResponse) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *HasPermissionResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *HasPermissionResponse) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

var File_api_zebra_passport_permission_permission_proto protoreflect.FileDescriptor

const file_api_zebra_passport_permission_permission_proto_rawDesc = "" +
	"\n" +
	".api/zebra-passport/permission/permission.proto\x12\n" +
	"permission\x1a\x1egoogle/protobuf/wrappers.proto\"E\n" +
	"\x14HasPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05perms\x18\x02 \x01(\tR\x05perms\"\x81\x01\n" +
	"\x15HasPermissionResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12%\n" +
	"\x0ehas_permission\x18\x03 \x01(\bR\rhasPermission2i\n" +
	"\x11PermissionService\x12T\n" +
	"\rHasPermission\x12 .permission.HasPermissionRequest\x1a!.permission.HasPermissionResponseB,Z*./api/zebra-passport/permission;permissionb\x06proto3"

var (
	file_api_zebra_passport_permission_permission_proto_rawDescOnce sync.Once
	file_api_zebra_passport_permission_permission_proto_rawDescData []byte
)

func file_api_zebra_passport_permission_permission_proto_rawDescGZIP() []byte {
	file_api_zebra_passport_permission_permission_proto_rawDescOnce.Do(func() {
		file_api_zebra_passport_permission_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zebra_passport_permission_permission_proto_rawDesc), len(file_api_zebra_passport_permission_permission_proto_rawDesc)))
	})
	return file_api_zebra_passport_permission_permission_proto_rawDescData
}

var file_api_zebra_passport_permission_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_zebra_passport_permission_permission_proto_goTypes = []any{
	(*HasPermissionRequest)(nil),  // 0: permission.HasPermissionRequest
	(*HasPermissionResponse)(nil), // 1: permission.HasPermissionResponse
	(*wrapperspb.Int32Value)(nil), // 2: google.protobuf.Int32Value
}
var file_api_zebra_passport_permission_permission_proto_depIdxs = []int32{
	2, // 0: permission.HasPermissionResponse.code:type_name -> google.protobuf.Int32Value
	0, // 1: permission.PermissionService.HasPermission:input_type -> permission.HasPermissionRequest
	1, // 2: permission.PermissionService.HasPermission:output_type -> permission.HasPermissionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_zebra_passport_permission_permission_proto_init() }
func file_api_zebra_passport_permission_permission_proto_init() {
	if File_api_zebra_passport_permission_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zebra_passport_permission_permission_proto_rawDesc), len(file_api_zebra_passport_permission_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zebra_passport_permission_permission_proto_goTypes,
		DependencyIndexes: file_api_zebra_passport_permission_permission_proto_depIdxs,
		MessageInfos:      file_api_zebra_passport_permission_permission_proto_msgTypes,
	}.Build()
	File_api_zebra_passport_permission_permission_proto = out.File
	file_api_zebra_passport_permission_permission_proto_goTypes = nil
	file_api_zebra_passport_permission_permission_proto_depIdxs = nil
}
