// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: api/zebra-stock/stock_inner/stock_inner.proto
package stockinnerpb

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// StockInnerServiceName is the fully-qualified name of the StockInnerService service.
	StockInnerServiceName = "zebra.stock.inner.StockInnerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StockInnerServiceBatchGetStockNumProcedure is the fully-qualified name of the StockInnerService's BatchGetStockNum RPC.
	StockInnerServiceBatchGetStockNumProcedure = "/zebra.stock.inner.StockInnerService/BatchGetStockNum"
)

var (
	_ StockInnerService = (*StockInnerServiceImpl)(nil)
)

// StockInnerService is a client for the zebra.stock.inner.StockInnerService service.
type StockInnerService interface {
	BatchGetStockNum(ctx context.Context, req *BatchGetStockNumRequest, opts ...client.CallOption) (*BatchGetStockNumResponse, error)
}

// NewStockInnerService constructs a client for the stockinnerpb.StockInnerService service.
func NewStockInnerService(cli *client.Client, opts ...client.ReferenceOption) (StockInnerService, error) {
	conn, err := cli.DialWithInfo("zebra.stock.inner.StockInnerService", &StockInnerService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &StockInnerServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerStockInnerService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &StockInnerService_ClientInfo)
}

// StockInnerServiceImpl implements StockInnerService.
type StockInnerServiceImpl struct {
	conn *client.Connection
}

func (c *StockInnerServiceImpl) BatchGetStockNum(ctx context.Context, req *BatchGetStockNumRequest, opts ...client.CallOption) (*BatchGetStockNumResponse, error) {
	resp := new(BatchGetStockNumResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "BatchGetStockNum", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var StockInnerService_ClientInfo = client.ClientInfo{
	InterfaceName: "zebra.stock.inner.StockInnerService",
	MethodNames:   []string{"BatchGetStockNum"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*StockInnerServiceImpl)
		dubboCli.conn = conn
	},
}

// StockInnerServiceHandler is an implementation of the zebra.stock.inner.StockInnerService service.
type StockInnerServiceHandler interface {
	BatchGetStockNum(context.Context, *BatchGetStockNumRequest) (*BatchGetStockNumResponse, error)
}

func RegisterStockInnerServiceHandler(srv *server.Server, hdlr StockInnerServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &StockInnerService_ServiceInfo, opts...)
}

func SetProviderStockInnerService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &StockInnerService_ServiceInfo)
}

var StockInnerService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "zebra.stock.inner.StockInnerService",
	ServiceType:   (*StockInnerServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "BatchGetStockNum",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(BatchGetStockNumRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*BatchGetStockNumRequest)
				res, err := handler.(StockInnerServiceHandler).BatchGetStockNum(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
