// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: api/zebra-message/sms/sms.proto
package sms

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// SmsServiceName is the fully-qualified name of the SmsService service.
	SmsServiceName = "sms.SmsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SmsServiceSendSmsProcedure is the fully-qualified name of the SmsService's SendSms RPC.
	SmsServiceSendSmsProcedure = "/sms.SmsService/SendSms"
	// SmsServiceBatchSendSmsProcedure is the fully-qualified name of the SmsService's BatchSendSms RPC.
	SmsServiceBatchSendSmsProcedure = "/sms.SmsService/BatchSendSms"
	// SmsServiceCreateTemplateProcedure is the fully-qualified name of the SmsService's CreateTemplate RPC.
	SmsServiceCreateTemplateProcedure = "/sms.SmsService/CreateTemplate"
	// SmsServiceUpdateTemplateProcedure is the fully-qualified name of the SmsService's UpdateTemplate RPC.
	SmsServiceUpdateTemplateProcedure = "/sms.SmsService/UpdateTemplate"
	// SmsServiceDeleteTemplateProcedure is the fully-qualified name of the SmsService's DeleteTemplate RPC.
	SmsServiceDeleteTemplateProcedure = "/sms.SmsService/DeleteTemplate"
	// SmsServiceGetTemplateProcedure is the fully-qualified name of the SmsService's GetTemplate RPC.
	SmsServiceGetTemplateProcedure = "/sms.SmsService/GetTemplate"
	// SmsServiceListTemplatesProcedure is the fully-qualified name of the SmsService's ListTemplates RPC.
	SmsServiceListTemplatesProcedure = "/sms.SmsService/ListTemplates"
	// SmsServiceListLogsProcedure is the fully-qualified name of the SmsService's ListLogs RPC.
	SmsServiceListLogsProcedure = "/sms.SmsService/ListLogs"
)

var (
	_ SmsService = (*SmsServiceImpl)(nil)
)

// SmsService is a client for the sms.SmsService service.
type SmsService interface {
	SendSms(ctx context.Context, req *SendSmsRequest, opts ...client.CallOption) (*SendSmsResponse, error)
	BatchSendSms(ctx context.Context, req *BatchSendSmsRequest, opts ...client.CallOption) (*BatchSendSmsResponse, error)
	CreateTemplate(ctx context.Context, req *CreateSmsTemplateRequest, opts ...client.CallOption) (*SmsResponse, error)
	UpdateTemplate(ctx context.Context, req *UpdateSmsTemplateRequest, opts ...client.CallOption) (*SmsResponse, error)
	DeleteTemplate(ctx context.Context, req *DeleteSmsTemplateRequest, opts ...client.CallOption) (*SmsResponse, error)
	GetTemplate(ctx context.Context, req *GetSmsTemplateRequest, opts ...client.CallOption) (*GetSmsTemplateResponse, error)
	ListTemplates(ctx context.Context, req *ListSmsTemplateRequest, opts ...client.CallOption) (*ListSmsTemplateResponse, error)
	ListLogs(ctx context.Context, req *ListSmsLogRequest, opts ...client.CallOption) (*ListSmsLogResponse, error)
}

// NewSmsService constructs a client for the sms.SmsService service.
func NewSmsService(cli *client.Client, opts ...client.ReferenceOption) (SmsService, error) {
	conn, err := cli.DialWithInfo("sms.SmsService", &SmsService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &SmsServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerSmsService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &SmsService_ClientInfo)
}

// SmsServiceImpl implements SmsService.
type SmsServiceImpl struct {
	conn *client.Connection
}

func (c *SmsServiceImpl) SendSms(ctx context.Context, req *SendSmsRequest, opts ...client.CallOption) (*SendSmsResponse, error) {
	resp := new(SendSmsResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "SendSms", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *SmsServiceImpl) BatchSendSms(ctx context.Context, req *BatchSendSmsRequest, opts ...client.CallOption) (*BatchSendSmsResponse, error) {
	resp := new(BatchSendSmsResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "BatchSendSms", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *SmsServiceImpl) CreateTemplate(ctx context.Context, req *CreateSmsTemplateRequest, opts ...client.CallOption) (*SmsResponse, error) {
	resp := new(SmsResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "CreateTemplate", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *SmsServiceImpl) UpdateTemplate(ctx context.Context, req *UpdateSmsTemplateRequest, opts ...client.CallOption) (*SmsResponse, error) {
	resp := new(SmsResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "UpdateTemplate", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *SmsServiceImpl) DeleteTemplate(ctx context.Context, req *DeleteSmsTemplateRequest, opts ...client.CallOption) (*SmsResponse, error) {
	resp := new(SmsResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "DeleteTemplate", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *SmsServiceImpl) GetTemplate(ctx context.Context, req *GetSmsTemplateRequest, opts ...client.CallOption) (*GetSmsTemplateResponse, error) {
	resp := new(GetSmsTemplateResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "GetTemplate", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *SmsServiceImpl) ListTemplates(ctx context.Context, req *ListSmsTemplateRequest, opts ...client.CallOption) (*ListSmsTemplateResponse, error) {
	resp := new(ListSmsTemplateResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "ListTemplates", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *SmsServiceImpl) ListLogs(ctx context.Context, req *ListSmsLogRequest, opts ...client.CallOption) (*ListSmsLogResponse, error) {
	resp := new(ListSmsLogResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "ListLogs", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var SmsService_ClientInfo = client.ClientInfo{
	InterfaceName: "sms.SmsService",
	MethodNames:   []string{"SendSms", "BatchSendSms", "CreateTemplate", "UpdateTemplate", "DeleteTemplate", "GetTemplate", "ListTemplates", "ListLogs"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*SmsServiceImpl)
		dubboCli.conn = conn
	},
}

// SmsServiceHandler is an implementation of the sms.SmsService service.
type SmsServiceHandler interface {
	SendSms(context.Context, *SendSmsRequest) (*SendSmsResponse, error)
	BatchSendSms(context.Context, *BatchSendSmsRequest) (*BatchSendSmsResponse, error)
	CreateTemplate(context.Context, *CreateSmsTemplateRequest) (*SmsResponse, error)
	UpdateTemplate(context.Context, *UpdateSmsTemplateRequest) (*SmsResponse, error)
	DeleteTemplate(context.Context, *DeleteSmsTemplateRequest) (*SmsResponse, error)
	GetTemplate(context.Context, *GetSmsTemplateRequest) (*GetSmsTemplateResponse, error)
	ListTemplates(context.Context, *ListSmsTemplateRequest) (*ListSmsTemplateResponse, error)
	ListLogs(context.Context, *ListSmsLogRequest) (*ListSmsLogResponse, error)
}

func RegisterSmsServiceHandler(srv *server.Server, hdlr SmsServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &SmsService_ServiceInfo, opts...)
}

func SetProviderSmsService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &SmsService_ServiceInfo)
}

var SmsService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "sms.SmsService",
	ServiceType:   (*SmsServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "SendSms",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(SendSmsRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*SendSmsRequest)
				res, err := handler.(SmsServiceHandler).SendSms(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "BatchSendSms",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(BatchSendSmsRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*BatchSendSmsRequest)
				res, err := handler.(SmsServiceHandler).BatchSendSms(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "CreateTemplate",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(CreateSmsTemplateRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*CreateSmsTemplateRequest)
				res, err := handler.(SmsServiceHandler).CreateTemplate(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "UpdateTemplate",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(UpdateSmsTemplateRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*UpdateSmsTemplateRequest)
				res, err := handler.(SmsServiceHandler).UpdateTemplate(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "DeleteTemplate",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(DeleteSmsTemplateRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*DeleteSmsTemplateRequest)
				res, err := handler.(SmsServiceHandler).DeleteTemplate(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "GetTemplate",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetSmsTemplateRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetSmsTemplateRequest)
				res, err := handler.(SmsServiceHandler).GetTemplate(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "ListTemplates",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(ListSmsTemplateRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*ListSmsTemplateRequest)
				res, err := handler.(SmsServiceHandler).ListTemplates(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "ListLogs",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(ListSmsLogRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*ListSmsLogRequest)
				res, err := handler.(SmsServiceHandler).ListLogs(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
