// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/zebra-passport/logininfor/logininfor.proto

package logininfor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录日志（对应 sys_logininfor 表）
type Logininfor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoId        int64                  `protobuf:"varint,1,opt,name=info_id,json=infoId,proto3" json:"info_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Ipaddr        string                 `protobuf:"bytes,3,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // 登录状态（0成功 1失败）
	Msg           string                 `protobuf:"bytes,5,opt,name=msg,proto3" json:"msg,omitempty"`
	AccessTime    int64                  `protobuf:"varint,6,opt,name=access_time,json=accessTime,proto3" json:"access_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Logininfor) Reset() {
	*x = Logininfor{}
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Logininfor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logininfor) ProtoMessage() {}

func (x *Logininfor) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logininfor.ProtoReflect.Descriptor instead.
func (*Logininfor) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_logininfor_logininfor_proto_rawDescGZIP(), []int{0}
}

func (x *Logininfor) GetInfoId() int64 {
	if x != nil {
		return x.InfoId
	}
	return 0
}

func (x *Logininfor) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Logininfor) GetIpaddr() string {
	if x != nil {
		return x.Ipaddr
	}
	return ""
}

func (x *Logininfor) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Logininfor) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Logininfor) GetAccessTime() int64 {
	if x != nil {
		return x.AccessTime
	}
	return 0
}

// 查询登录日志请求
type ListLogininforRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Ipaddr        string                 `protobuf:"bytes,4,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	BeginTime     string                 `protobuf:"bytes,6,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogininforRequest) Reset() {
	*x = ListLogininforRequest{}
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogininforRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogininforRequest) ProtoMessage() {}

func (x *ListLogininforRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogininforRequest.ProtoReflect.Descriptor instead.
func (*ListLogininforRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_logininfor_logininfor_proto_rawDescGZIP(), []int{1}
}

func (x *ListLogininforRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLogininforRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLogininforRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ListLogininforRequest) GetIpaddr() string {
	if x != nil {
		return x.Ipaddr
	}
	return ""
}

func (x *ListLogininforRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListLogininforRequest) GetBeginTime() string {
	if x != nil {
		return x.BeginTime
	}
	return ""
}

func (x *ListLogininforRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

// 查询登录日志响应
type ListLogininforResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码: 0=成功, -1=失败, -2=数据为空
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Infos         []*Logininfor          `protobuf:"bytes,3,rep,name=infos,proto3" json:"infos,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogininforResponse) Reset() {
	*x = ListLogininforResponse{}
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogininforResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogininforResponse) ProtoMessage() {}

func (x *ListLogininforResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogininforResponse.ProtoReflect.Descriptor instead.
func (*ListLogininforResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_logininfor_logininfor_proto_rawDescGZIP(), []int{2}
}

func (x *ListLogininforResponse) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *ListLogininforResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListLogininforResponse) GetInfos() []*Logininfor {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *ListLogininforResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 删除登录日志请求
type DeleteLogininforRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoIds       []int64                `protobuf:"varint,1,rep,packed,name=info_ids,json=infoIds,proto3" json:"info_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLogininforRequest) Reset() {
	*x = DeleteLogininforRequest{}
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogininforRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogininforRequest) ProtoMessage() {}

func (x *DeleteLogininforRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogininforRequest.ProtoReflect.Descriptor instead.
func (*DeleteLogininforRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_logininfor_logininfor_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteLogininforRequest) GetInfoIds() []int64 {
	if x != nil {
		return x.InfoIds
	}
	return nil
}

// 解锁用户请求
type UnlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockUserRequest) Reset() {
	*x = UnlockUserRequest{}
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockUserRequest) ProtoMessage() {}

func (x *UnlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockUserRequest.ProtoReflect.Descriptor instead.
func (*UnlockUserRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_logininfor_logininfor_proto_rawDescGZIP(), []int{4}
}

func (x *UnlockUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码: 0=成功, -1=失败, -2=数据为空
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_logininfor_logininfor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_logininfor_logininfor_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_zebra_passport_logininfor_logininfor_proto protoreflect.FileDescriptor

const file_api_zebra_passport_logininfor_logininfor_proto_rawDesc = "" +
	"\n" +
	".api/zebra-passport/logininfor/logininfor.proto\x12\n" +
	"logininfor\x1a\x1egoogle/protobuf/wrappers.proto\"\xa5\x01\n" +
	"\n" +
	"Logininfor\x12\x17\n" +
	"\ainfo_id\x18\x01 \x01(\x03R\x06infoId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x16\n" +
	"\x06ipaddr\x18\x03 \x01(\tR\x06ipaddr\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x10\n" +
	"\x03msg\x18\x05 \x01(\tR\x03msg\x12\x1f\n" +
	"\vaccess_time\x18\x06 \x01(\x03R\n" +
	"accessTime\"\xcf\x01\n" +
	"\x15ListLogininforRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x16\n" +
	"\x06ipaddr\x18\x04 \x01(\tR\x06ipaddr\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"begin_time\x18\x06 \x01(\tR\tbeginTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\"\x9f\x01\n" +
	"\x16ListLogininforResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12,\n" +
	"\x05infos\x18\x03 \x03(\v2\x16.logininfor.LogininforR\x05infos\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"4\n" +
	"\x17DeleteLogininforRequest\x12\x19\n" +
	"\binfo_ids\x18\x01 \x03(\x03R\ainfoIds\"0\n" +
	"\x11UnlockUserRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\"M\n" +
	"\bResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xaa\x02\n" +
	"\x11LogininforService\x12M\n" +
	"\x04List\x12!.logininfor.ListLogininforRequest\x1a\".logininfor.ListLogininforResponse\x12C\n" +
	"\x06Delete\x12#.logininfor.DeleteLogininforRequest\x1a\x14.logininfor.Response\x12B\n" +
	"\x05Clean\x12#.logininfor.DeleteLogininforRequest\x1a\x14.logininfor.Response\x12=\n" +
	"\x06Unlock\x12\x1d.logininfor.UnlockUserRequest\x1a\x14.logininfor.ResponseB,Z*./api/zebra-passport/logininfor;logininforb\x06proto3"

var (
	file_api_zebra_passport_logininfor_logininfor_proto_rawDescOnce sync.Once
	file_api_zebra_passport_logininfor_logininfor_proto_rawDescData []byte
)

func file_api_zebra_passport_logininfor_logininfor_proto_rawDescGZIP() []byte {
	file_api_zebra_passport_logininfor_logininfor_proto_rawDescOnce.Do(func() {
		file_api_zebra_passport_logininfor_logininfor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zebra_passport_logininfor_logininfor_proto_rawDesc), len(file_api_zebra_passport_logininfor_logininfor_proto_rawDesc)))
	})
	return file_api_zebra_passport_logininfor_logininfor_proto_rawDescData
}

var file_api_zebra_passport_logininfor_logininfor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_zebra_passport_logininfor_logininfor_proto_goTypes = []any{
	(*Logininfor)(nil),              // 0: logininfor.Logininfor
	(*ListLogininforRequest)(nil),   // 1: logininfor.ListLogininforRequest
	(*ListLogininforResponse)(nil),  // 2: logininfor.ListLogininforResponse
	(*DeleteLogininforRequest)(nil), // 3: logininfor.DeleteLogininforRequest
	(*UnlockUserRequest)(nil),       // 4: logininfor.UnlockUserRequest
	(*Response)(nil),                // 5: logininfor.Response
	(*wrapperspb.Int32Value)(nil),   // 6: google.protobuf.Int32Value
}
var file_api_zebra_passport_logininfor_logininfor_proto_depIdxs = []int32{
	6, // 0: logininfor.ListLogininforResponse.code:type_name -> google.protobuf.Int32Value
	0, // 1: logininfor.ListLogininforResponse.infos:type_name -> logininfor.Logininfor
	6, // 2: logininfor.Response.code:type_name -> google.protobuf.Int32Value
	1, // 3: logininfor.LogininforService.List:input_type -> logininfor.ListLogininforRequest
	3, // 4: logininfor.LogininforService.Delete:input_type -> logininfor.DeleteLogininforRequest
	3, // 5: logininfor.LogininforService.Clean:input_type -> logininfor.DeleteLogininforRequest
	4, // 6: logininfor.LogininforService.Unlock:input_type -> logininfor.UnlockUserRequest
	2, // 7: logininfor.LogininforService.List:output_type -> logininfor.ListLogininforResponse
	5, // 8: logininfor.LogininforService.Delete:output_type -> logininfor.Response
	5, // 9: logininfor.LogininforService.Clean:output_type -> logininfor.Response
	5, // 10: logininfor.LogininforService.Unlock:output_type -> logininfor.Response
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_zebra_passport_logininfor_logininfor_proto_init() }
func file_api_zebra_passport_logininfor_logininfor_proto_init() {
	if File_api_zebra_passport_logininfor_logininfor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zebra_passport_logininfor_logininfor_proto_rawDesc), len(file_api_zebra_passport_logininfor_logininfor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zebra_passport_logininfor_logininfor_proto_goTypes,
		DependencyIndexes: file_api_zebra_passport_logininfor_logininfor_proto_depIdxs,
		MessageInfos:      file_api_zebra_passport_logininfor_logininfor_proto_msgTypes,
	}.Build()
	File_api_zebra_passport_logininfor_logininfor_proto = out.File
	file_api_zebra_passport_logininfor_logininfor_proto_goTypes = nil
	file_api_zebra_passport_logininfor_logininfor_proto_depIdxs = nil
}
