// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/zebra-passport/user/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户信息（对应 sys_user 表）
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeptId        int64                  `protobuf:"varint,2,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NickName      string                 `protobuf:"bytes,4,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	UserType      string                 `protobuf:"bytes,5,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"` // 用户类型（00系统用户）
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phonenumber   string                 `protobuf:"bytes,7,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Sex           string                 `protobuf:"bytes,8,opt,name=sex,proto3" json:"sex,omitempty"` // 性别（0男 1女 2未知）
	Avatar        string                 `protobuf:"bytes,9,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Password      string                 `protobuf:"bytes,10,opt,name=password,proto3" json:"password,omitempty"`
	Status        string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`                  // 状态（0正常 1停用）
	DelFlag       string                 `protobuf:"bytes,12,opt,name=del_flag,json=delFlag,proto3" json:"del_flag,omitempty"` // 删除标志（0存在 2删除）
	LoginIp       string                 `protobuf:"bytes,13,opt,name=login_ip,json=loginIp,proto3" json:"login_ip,omitempty"`
	LoginDate     int64                  `protobuf:"varint,14,opt,name=login_date,json=loginDate,proto3" json:"login_date,omitempty"`
	PwdUpdateDate int64                  `protobuf:"varint,15,opt,name=pwd_update_date,json=pwdUpdateDate,proto3" json:"pwd_update_date,omitempty"`
	CreateBy      string                 `protobuf:"bytes,16,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	CreateTime    int64                  `protobuf:"varint,17,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,18,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,19,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Remark        string                 `protobuf:"bytes,20,opt,name=remark,proto3" json:"remark,omitempty"`
	// 非数据库字段，关联查询
	DeptName      string  `protobuf:"bytes,21,opt,name=dept_name,json=deptName,proto3" json:"dept_name,omitempty"`
	RoleIds       []int64 `protobuf:"varint,22,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	PostIds       []int64 `protobuf:"varint,23,rep,packed,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *User) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *User) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetDelFlag() string {
	if x != nil {
		return x.DelFlag
	}
	return ""
}

func (x *User) GetLoginIp() string {
	if x != nil {
		return x.LoginIp
	}
	return ""
}

func (x *User) GetLoginDate() int64 {
	if x != nil {
		return x.LoginDate
	}
	return 0
}

func (x *User) GetPwdUpdateDate() int64 {
	if x != nil {
		return x.PwdUpdateDate
	}
	return 0
}

func (x *User) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *User) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *User) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *User) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *User) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *User) GetDeptName() string {
	if x != nil {
		return x.DeptName
	}
	return ""
}

func (x *User) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *User) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

// 获取用户详情请求（共享消息，被 user_auth、user_profile 引用）
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 创建用户请求
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeptId        int64                  `protobuf:"varint,1,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phonenumber   string                 `protobuf:"bytes,6,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Sex           string                 `protobuf:"bytes,7,opt,name=sex,proto3" json:"sex,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	RoleIds       []int64                `protobuf:"varint,10,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	PostIds       []int64                `protobuf:"varint,11,rep,packed,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *CreateUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *CreateUserRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *CreateUserRequest) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *CreateUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateUserRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreateUserRequest) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *CreateUserRequest) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

// 更新用户请求（optional 字段表示可部分更新）
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 必填
	DeptId        *int64                 `protobuf:"varint,2,opt,name=dept_id,json=deptId,proto3,oneof" json:"dept_id,omitempty"`
	NickName      *string                `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3,oneof" json:"nick_name,omitempty"`
	Email         *string                `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phonenumber   *string                `protobuf:"bytes,5,opt,name=phonenumber,proto3,oneof" json:"phonenumber,omitempty"`
	Sex           *string                `protobuf:"bytes,6,opt,name=sex,proto3,oneof" json:"sex,omitempty"`
	Status        *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Remark        *string                `protobuf:"bytes,8,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	RoleIds       []int64                `protobuf:"varint,9,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	PostIds       []int64                `protobuf:"varint,10,rep,packed,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRequest) GetDeptId() int64 {
	if x != nil && x.DeptId != nil {
		return *x.DeptId
	}
	return 0
}

func (x *UpdateUserRequest) GetNickName() string {
	if x != nil && x.NickName != nil {
		return *x.NickName
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPhonenumber() string {
	if x != nil && x.Phonenumber != nil {
		return *x.Phonenumber
	}
	return ""
}

func (x *UpdateUserRequest) GetSex() string {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return ""
}

func (x *UpdateUserRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateUserRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

func (x *UpdateUserRequest) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *UpdateUserRequest) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

// 删除用户请求
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 获取用户详情响应
type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	RoleIds       []int64                `protobuf:"varint,4,rep,packed,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	PostIds       []int64                `protobuf:"varint,5,rep,packed,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	Roles         []*RoleInfo            `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	Posts         []*PostInfo            `protobuf:"bytes,7,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserResponse) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *GetUserResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserResponse) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *GetUserResponse) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

func (x *GetUserResponse) GetRoles() []*RoleInfo {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetUserResponse) GetPosts() []*PostInfo {
	if x != nil {
		return x.Posts
	}
	return nil
}

// 角色简要信息
type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,2,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleKey       string                 `protobuf:"bytes,3,opt,name=role_key,json=roleKey,proto3" json:"role_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{6}
}

func (x *RoleInfo) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RoleInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleInfo) GetRoleKey() string {
	if x != nil {
		return x.RoleKey
	}
	return ""
}

// 岗位简要信息
type PostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	PostCode      string                 `protobuf:"bytes,2,opt,name=post_code,json=postCode,proto3" json:"post_code,omitempty"`
	PostName      string                 `protobuf:"bytes,3,opt,name=post_name,json=postName,proto3" json:"post_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{7}
}

func (x *PostInfo) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *PostInfo) GetPostCode() string {
	if x != nil {
		return x.PostCode
	}
	return ""
}

func (x *PostInfo) GetPostName() string {
	if x != nil {
		return x.PostName
	}
	return ""
}

// 列出用户请求
type ListUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Phonenumber   string                 `protobuf:"bytes,4,opt,name=phonenumber,proto3" json:"phonenumber,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	DeptId        int64                  `protobuf:"varint,6,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	BeginTime     string                 `protobuf:"bytes,7,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRequest) Reset() {
	*x = ListUserRequest{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequest) ProtoMessage() {}

func (x *ListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequest.ProtoReflect.Descriptor instead.
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ListUserRequest) GetPhonenumber() string {
	if x != nil {
		return x.Phonenumber
	}
	return ""
}

func (x *ListUserRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListUserRequest) GetDeptId() int64 {
	if x != nil {
		return x.DeptId
	}
	return 0
}

func (x *ListUserRequest) GetBeginTime() string {
	if x != nil {
		return x.BeginTime
	}
	return ""
}

func (x *ListUserRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

// 列出用户响应
type ListUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Users         []*User                `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserResponse) Reset() {
	*x = ListUserResponse{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserResponse) ProtoMessage() {}

func (x *ListUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserResponse.ProtoReflect.Descriptor instead.
func (*ListUserResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserResponse) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *ListUserResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListUserResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUserResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 重置密码请求
type ResetPwdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPwdRequest) Reset() {
	*x = ResetPwdRequest{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPwdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPwdRequest) ProtoMessage() {}

func (x *ResetPwdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPwdRequest.ProtoReflect.Descriptor instead.
func (*ResetPwdRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{10}
}

func (x *ResetPwdRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ResetPwdRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 修改用户状态请求
type ChangeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeStatusRequest) Reset() {
	*x = ChangeStatusRequest{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeStatusRequest) ProtoMessage() {}

func (x *ChangeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeStatusRequest.ProtoReflect.Descriptor instead.
func (*ChangeStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChangeStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码: 0=成功, -1=失败, -2=数据为空
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_user_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_user_user_proto_rawDescGZIP(), []int{12}
}

func (x *Response) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_zebra_passport_user_user_proto protoreflect.FileDescriptor

const file_api_zebra_passport_user_user_proto_rawDesc = "" +
	"\n" +
	"\"api/zebra-passport/user/user.proto\x12\x04user\x1a\x1egoogle/protobuf/wrappers.proto\"\x89\x05\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\adept_id\x18\x02 \x01(\x03R\x06deptId\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12\x1b\n" +
	"\tnick_name\x18\x04 \x01(\tR\bnickName\x12\x1b\n" +
	"\tuser_type\x18\x05 \x01(\tR\buserType\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12 \n" +
	"\vphonenumber\x18\a \x01(\tR\vphonenumber\x12\x10\n" +
	"\x03sex\x18\b \x01(\tR\x03sex\x12\x16\n" +
	"\x06avatar\x18\t \x01(\tR\x06avatar\x12\x1a\n" +
	"\bpassword\x18\n" +
	" \x01(\tR\bpassword\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x19\n" +
	"\bdel_flag\x18\f \x01(\tR\adelFlag\x12\x19\n" +
	"\blogin_ip\x18\r \x01(\tR\aloginIp\x12\x1d\n" +
	"\n" +
	"login_date\x18\x0e \x01(\x03R\tloginDate\x12&\n" +
	"\x0fpwd_update_date\x18\x0f \x01(\x03R\rpwdUpdateDate\x12\x1b\n" +
	"\tcreate_by\x18\x10 \x01(\tR\bcreateBy\x12\x1f\n" +
	"\vcreate_time\x18\x11 \x01(\x03R\n" +
	"createTime\x12\x1b\n" +
	"\tupdate_by\x18\x12 \x01(\tR\bupdateBy\x12\x1f\n" +
	"\vupdate_time\x18\x13 \x01(\x03R\n" +
	"updateTime\x12\x16\n" +
	"\x06remark\x18\x14 \x01(\tR\x06remark\x12\x1b\n" +
	"\tdept_name\x18\x15 \x01(\tR\bdeptName\x12\x19\n" +
	"\brole_ids\x18\x16 \x03(\x03R\aroleIds\x12\x19\n" +
	"\bpost_ids\x18\x17 \x03(\x03R\apostIds\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xb2\x02\n" +
	"\x11CreateUserRequest\x12\x17\n" +
	"\adept_id\x18\x01 \x01(\x03R\x06deptId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12\x1b\n" +
	"\tnick_name\x18\x03 \x01(\tR\bnickName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12 \n" +
	"\vphonenumber\x18\x06 \x01(\tR\vphonenumber\x12\x10\n" +
	"\x03sex\x18\a \x01(\tR\x03sex\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\x12\x19\n" +
	"\brole_ids\x18\n" +
	" \x03(\x03R\aroleIds\x12\x19\n" +
	"\bpost_ids\x18\v \x03(\x03R\apostIds\"\x87\x03\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\adept_id\x18\x02 \x01(\x03H\x00R\x06deptId\x88\x01\x01\x12 \n" +
	"\tnick_name\x18\x03 \x01(\tH\x01R\bnickName\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x02R\x05email\x88\x01\x01\x12%\n" +
	"\vphonenumber\x18\x05 \x01(\tH\x03R\vphonenumber\x88\x01\x01\x12\x15\n" +
	"\x03sex\x18\x06 \x01(\tH\x04R\x03sex\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x05R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06remark\x18\b \x01(\tH\x06R\x06remark\x88\x01\x01\x12\x19\n" +
	"\brole_ids\x18\t \x03(\x03R\aroleIds\x12\x19\n" +
	"\bpost_ids\x18\n" +
	" \x03(\x03R\apostIdsB\n" +
	"\n" +
	"\b_dept_idB\f\n" +
	"\n" +
	"_nick_nameB\b\n" +
	"\x06_emailB\x0e\n" +
	"\f_phonenumberB\x06\n" +
	"\x04_sexB\t\n" +
	"\a_statusB\t\n" +
	"\a_remark\".\n" +
	"\x11DeleteUserRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"\xf6\x01\n" +
	"\x0fGetUserResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1e\n" +
	"\x04user\x18\x03 \x01(\v2\n" +
	".user.UserR\x04user\x12\x19\n" +
	"\brole_ids\x18\x04 \x03(\x03R\aroleIds\x12\x19\n" +
	"\bpost_ids\x18\x05 \x03(\x03R\apostIds\x12$\n" +
	"\x05roles\x18\x06 \x03(\v2\x0e.user.RoleInfoR\x05roles\x12$\n" +
	"\x05posts\x18\a \x03(\v2\x0e.user.PostInfoR\x05posts\"[\n" +
	"\bRoleInfo\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x02 \x01(\tR\broleName\x12\x19\n" +
	"\brole_key\x18\x03 \x01(\tR\aroleKey\"]\n" +
	"\bPostInfo\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\x12\x1b\n" +
	"\tpost_code\x18\x02 \x01(\tR\bpostCode\x12\x1b\n" +
	"\tpost_name\x18\x03 \x01(\tR\bpostName\"\xec\x01\n" +
	"\x0fListUserRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tuser_name\x18\x03 \x01(\tR\buserName\x12 \n" +
	"\vphonenumber\x18\x04 \x01(\tR\vphonenumber\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x17\n" +
	"\adept_id\x18\x06 \x01(\x03R\x06deptId\x12\x1d\n" +
	"\n" +
	"begin_time\x18\a \x01(\tR\tbeginTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\tR\aendTime\"\x8d\x01\n" +
	"\x10ListUserResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12 \n" +
	"\x05users\x18\x03 \x03(\v2\n" +
	".user.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"F\n" +
	"\x0fResetPwdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"F\n" +
	"\x13ChangeStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"M\n" +
	"\bResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xff\x02\n" +
	"\vUserService\x121\n" +
	"\x06Create\x12\x17.user.CreateUserRequest\x1a\x0e.user.Response\x121\n" +
	"\x06Update\x12\x17.user.UpdateUserRequest\x1a\x0e.user.Response\x121\n" +
	"\x06Delete\x12\x17.user.DeleteUserRequest\x1a\x0e.user.Response\x122\n" +
	"\x03Get\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x125\n" +
	"\x04List\x12\x15.user.ListUserRequest\x1a\x16.user.ListUserResponse\x121\n" +
	"\bResetPwd\x12\x15.user.ResetPwdRequest\x1a\x0e.user.Response\x129\n" +
	"\fChangeStatus\x12\x19.user.ChangeStatusRequest\x1a\x0e.user.ResponseB Z\x1e./api/zebra-passport/user;userb\x06proto3"

var (
	file_api_zebra_passport_user_user_proto_rawDescOnce sync.Once
	file_api_zebra_passport_user_user_proto_rawDescData []byte
)

func file_api_zebra_passport_user_user_proto_rawDescGZIP() []byte {
	file_api_zebra_passport_user_user_proto_rawDescOnce.Do(func() {
		file_api_zebra_passport_user_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zebra_passport_user_user_proto_rawDesc), len(file_api_zebra_passport_user_user_proto_rawDesc)))
	})
	return file_api_zebra_passport_user_user_proto_rawDescData
}

var file_api_zebra_passport_user_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_zebra_passport_user_user_proto_goTypes = []any{
	(*User)(nil),                  // 0: user.User
	(*GetUserRequest)(nil),        // 1: user.GetUserRequest
	(*CreateUserRequest)(nil),     // 2: user.CreateUserRequest
	(*UpdateUserRequest)(nil),     // 3: user.UpdateUserRequest
	(*DeleteUserRequest)(nil),     // 4: user.DeleteUserRequest
	(*GetUserResponse)(nil),       // 5: user.GetUserResponse
	(*RoleInfo)(nil),              // 6: user.RoleInfo
	(*PostInfo)(nil),              // 7: user.PostInfo
	(*ListUserRequest)(nil),       // 8: user.ListUserRequest
	(*ListUserResponse)(nil),      // 9: user.ListUserResponse
	(*ResetPwdRequest)(nil),       // 10: user.ResetPwdRequest
	(*ChangeStatusRequest)(nil),   // 11: user.ChangeStatusRequest
	(*Response)(nil),              // 12: user.Response
	(*wrapperspb.Int32Value)(nil), // 13: google.protobuf.Int32Value
}
var file_api_zebra_passport_user_user_proto_depIdxs = []int32{
	13, // 0: user.GetUserResponse.code:type_name -> google.protobuf.Int32Value
	0,  // 1: user.GetUserResponse.user:type_name -> user.User
	6,  // 2: user.GetUserResponse.roles:type_name -> user.RoleInfo
	7,  // 3: user.GetUserResponse.posts:type_name -> user.PostInfo
	13, // 4: user.ListUserResponse.code:type_name -> google.protobuf.Int32Value
	0,  // 5: user.ListUserResponse.users:type_name -> user.User
	13, // 6: user.Response.code:type_name -> google.protobuf.Int32Value
	2,  // 7: user.UserService.Create:input_type -> user.CreateUserRequest
	3,  // 8: user.UserService.Update:input_type -> user.UpdateUserRequest
	4,  // 9: user.UserService.Delete:input_type -> user.DeleteUserRequest
	1,  // 10: user.UserService.Get:input_type -> user.GetUserRequest
	8,  // 11: user.UserService.List:input_type -> user.ListUserRequest
	10, // 12: user.UserService.ResetPwd:input_type -> user.ResetPwdRequest
	11, // 13: user.UserService.ChangeStatus:input_type -> user.ChangeStatusRequest
	12, // 14: user.UserService.Create:output_type -> user.Response
	12, // 15: user.UserService.Update:output_type -> user.Response
	12, // 16: user.UserService.Delete:output_type -> user.Response
	5,  // 17: user.UserService.Get:output_type -> user.GetUserResponse
	9,  // 18: user.UserService.List:output_type -> user.ListUserResponse
	12, // 19: user.UserService.ResetPwd:output_type -> user.Response
	12, // 20: user.UserService.ChangeStatus:output_type -> user.Response
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_zebra_passport_user_user_proto_init() }
func file_api_zebra_passport_user_user_proto_init() {
	if File_api_zebra_passport_user_user_proto != nil {
		return
	}
	file_api_zebra_passport_user_user_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zebra_passport_user_user_proto_rawDesc), len(file_api_zebra_passport_user_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zebra_passport_user_user_proto_goTypes,
		DependencyIndexes: file_api_zebra_passport_user_user_proto_depIdxs,
		MessageInfos:      file_api_zebra_passport_user_user_proto_msgTypes,
	}.Build()
	File_api_zebra_passport_user_user_proto = out.File
	file_api_zebra_passport_user_user_proto_goTypes = nil
	file_api_zebra_passport_user_user_proto_depIdxs = nil
}
