// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: api/zebra-passport/user/user.proto
package user

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// UserServiceName is the fully-qualified name of the UserService service.
	UserServiceName = "user.UserService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UserServiceCreateProcedure is the fully-qualified name of the UserService's Create RPC.
	UserServiceCreateProcedure = "/user.UserService/Create"
	// UserServiceUpdateProcedure is the fully-qualified name of the UserService's Update RPC.
	UserServiceUpdateProcedure = "/user.UserService/Update"
	// UserServiceDeleteProcedure is the fully-qualified name of the UserService's Delete RPC.
	UserServiceDeleteProcedure = "/user.UserService/Delete"
	// UserServiceGetProcedure is the fully-qualified name of the UserService's Get RPC.
	UserServiceGetProcedure = "/user.UserService/Get"
	// UserServiceListProcedure is the fully-qualified name of the UserService's List RPC.
	UserServiceListProcedure = "/user.UserService/List"
	// UserServiceResetPwdProcedure is the fully-qualified name of the UserService's ResetPwd RPC.
	UserServiceResetPwdProcedure = "/user.UserService/ResetPwd"
	// UserServiceChangeStatusProcedure is the fully-qualified name of the UserService's ChangeStatus RPC.
	UserServiceChangeStatusProcedure = "/user.UserService/ChangeStatus"
)

var (
	_ UserService = (*UserServiceImpl)(nil)
)

// UserService is a client for the user.UserService service.
type UserService interface {
	Create(ctx context.Context, req *CreateUserRequest, opts ...client.CallOption) (*Response, error)
	Update(ctx context.Context, req *UpdateUserRequest, opts ...client.CallOption) (*Response, error)
	Delete(ctx context.Context, req *DeleteUserRequest, opts ...client.CallOption) (*Response, error)
	Get(ctx context.Context, req *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error)
	List(ctx context.Context, req *ListUserRequest, opts ...client.CallOption) (*ListUserResponse, error)
	ResetPwd(ctx context.Context, req *ResetPwdRequest, opts ...client.CallOption) (*Response, error)
	ChangeStatus(ctx context.Context, req *ChangeStatusRequest, opts ...client.CallOption) (*Response, error)
}

// NewUserService constructs a client for the user.UserService service.
func NewUserService(cli *client.Client, opts ...client.ReferenceOption) (UserService, error) {
	conn, err := cli.DialWithInfo("user.UserService", &UserService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &UserServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerUserService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &UserService_ClientInfo)
}

// UserServiceImpl implements UserService.
type UserServiceImpl struct {
	conn *client.Connection
}

func (c *UserServiceImpl) Create(ctx context.Context, req *CreateUserRequest, opts ...client.CallOption) (*Response, error) {
	resp := new(Response)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "Create", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *UserServiceImpl) Update(ctx context.Context, req *UpdateUserRequest, opts ...client.CallOption) (*Response, error) {
	resp := new(Response)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "Update", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *UserServiceImpl) Delete(ctx context.Context, req *DeleteUserRequest, opts ...client.CallOption) (*Response, error) {
	resp := new(Response)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "Delete", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *UserServiceImpl) Get(ctx context.Context, req *GetUserRequest, opts ...client.CallOption) (*GetUserResponse, error) {
	resp := new(GetUserResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "Get", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *UserServiceImpl) List(ctx context.Context, req *ListUserRequest, opts ...client.CallOption) (*ListUserResponse, error) {
	resp := new(ListUserResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "List", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *UserServiceImpl) ResetPwd(ctx context.Context, req *ResetPwdRequest, opts ...client.CallOption) (*Response, error) {
	resp := new(Response)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "ResetPwd", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *UserServiceImpl) ChangeStatus(ctx context.Context, req *ChangeStatusRequest, opts ...client.CallOption) (*Response, error) {
	resp := new(Response)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "ChangeStatus", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var UserService_ClientInfo = client.ClientInfo{
	InterfaceName: "user.UserService",
	MethodNames:   []string{"Create", "Update", "Delete", "Get", "List", "ResetPwd", "ChangeStatus"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*UserServiceImpl)
		dubboCli.conn = conn
	},
}

// UserServiceHandler is an implementation of the user.UserService service.
type UserServiceHandler interface {
	Create(context.Context, *CreateUserRequest) (*Response, error)
	Update(context.Context, *UpdateUserRequest) (*Response, error)
	Delete(context.Context, *DeleteUserRequest) (*Response, error)
	Get(context.Context, *GetUserRequest) (*GetUserResponse, error)
	List(context.Context, *ListUserRequest) (*ListUserResponse, error)
	ResetPwd(context.Context, *ResetPwdRequest) (*Response, error)
	ChangeStatus(context.Context, *ChangeStatusRequest) (*Response, error)
}

func RegisterUserServiceHandler(srv *server.Server, hdlr UserServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &UserService_ServiceInfo, opts...)
}

func SetProviderUserService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &UserService_ServiceInfo)
}

var UserService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "user.UserService",
	ServiceType:   (*UserServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "Create",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(CreateUserRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*CreateUserRequest)
				res, err := handler.(UserServiceHandler).Create(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "Update",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(UpdateUserRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*UpdateUserRequest)
				res, err := handler.(UserServiceHandler).Update(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "Delete",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(DeleteUserRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*DeleteUserRequest)
				res, err := handler.(UserServiceHandler).Delete(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "Get",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(GetUserRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*GetUserRequest)
				res, err := handler.(UserServiceHandler).Get(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "List",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(ListUserRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*ListUserRequest)
				res, err := handler.(UserServiceHandler).List(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "ResetPwd",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(ResetPwdRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*ResetPwdRequest)
				res, err := handler.(UserServiceHandler).ResetPwd(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
		{
			Name: "ChangeStatus",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(ChangeStatusRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*ChangeStatusRequest)
				res, err := handler.(UserServiceHandler).ChangeStatus(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
