// Code generated by protoc-gen-triple. DO NOT EDIT.
//
// Source: api/zebra-order/order_refund/order_refund.proto
package order_refund

import (
	"context"
)

import (
	"dubbo.apache.org/dubbo-go/v3"
	"dubbo.apache.org/dubbo-go/v3/client"
	"dubbo.apache.org/dubbo-go/v3/common"
	"dubbo.apache.org/dubbo-go/v3/common/constant"
	"dubbo.apache.org/dubbo-go/v3/protocol/triple/triple_protocol"
	"dubbo.apache.org/dubbo-go/v3/server"
)

// This is a compile-time assertion to ensure that this generated file and the Triple package
// are compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of Triple newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of Triple or updating the Triple
// version compiled into your binary.
const _ = triple_protocol.IsAtLeastVersion0_1_0

const (
	// OrderRefundServiceName is the fully-qualified name of the OrderRefundService service.
	OrderRefundServiceName = "order_refund.OrderRefundService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrderRefundServiceRefundOrderProcedure is the fully-qualified name of the OrderRefundService's RefundOrder RPC.
	OrderRefundServiceRefundOrderProcedure = "/order_refund.OrderRefundService/RefundOrder"
)

var (
	_ OrderRefundService = (*OrderRefundServiceImpl)(nil)
)

// OrderRefundService is a client for the order_refund.OrderRefundService service.
type OrderRefundService interface {
	RefundOrder(ctx context.Context, req *RefundOrderRequest, opts ...client.CallOption) (*RefundOrderResponse, error)
}

// NewOrderRefundService constructs a client for the order_refund.OrderRefundService service.
func NewOrderRefundService(cli *client.Client, opts ...client.ReferenceOption) (OrderRefundService, error) {
	conn, err := cli.DialWithInfo("order_refund.OrderRefundService", &OrderRefundService_ClientInfo, opts...)
	if err != nil {
		return nil, err
	}
	return &OrderRefundServiceImpl{
		conn: conn,
	}, nil
}

func SetConsumerOrderRefundService(srv common.RPCService) {
	dubbo.SetConsumerServiceWithInfo(srv, &OrderRefundService_ClientInfo)
}

// OrderRefundServiceImpl implements OrderRefundService.
type OrderRefundServiceImpl struct {
	conn *client.Connection
}

func (c *OrderRefundServiceImpl) RefundOrder(ctx context.Context, req *RefundOrderRequest, opts ...client.CallOption) (*RefundOrderResponse, error) {
	resp := new(RefundOrderResponse)
	if err := c.conn.CallUnary(ctx, []interface{}{req}, resp, "RefundOrder", opts...); err != nil {
		return nil, err
	}
	return resp, nil
}

var OrderRefundService_ClientInfo = client.ClientInfo{
	InterfaceName: "order_refund.OrderRefundService",
	MethodNames:   []string{"RefundOrder"},
	ConnectionInjectFunc: func(dubboCliRaw interface{}, conn *client.Connection) {
		dubboCli := dubboCliRaw.(*OrderRefundServiceImpl)
		dubboCli.conn = conn
	},
}

// OrderRefundServiceHandler is an implementation of the order_refund.OrderRefundService service.
type OrderRefundServiceHandler interface {
	RefundOrder(context.Context, *RefundOrderRequest) (*RefundOrderResponse, error)
}

func RegisterOrderRefundServiceHandler(srv *server.Server, hdlr OrderRefundServiceHandler, opts ...server.ServiceOption) error {
	return srv.Register(hdlr, &OrderRefundService_ServiceInfo, opts...)
}

func SetProviderOrderRefundService(srv common.RPCService) {
	dubbo.SetProviderServiceWithInfo(srv, &OrderRefundService_ServiceInfo)
}

var OrderRefundService_ServiceInfo = server.ServiceInfo{
	InterfaceName: "order_refund.OrderRefundService",
	ServiceType:   (*OrderRefundServiceHandler)(nil),
	Methods: []server.MethodInfo{
		{
			Name: "RefundOrder",
			Type: constant.CallUnary,
			ReqInitFunc: func() interface{} {
				return new(RefundOrderRequest)
			},
			MethodFunc: func(ctx context.Context, args []interface{}, handler interface{}) (interface{}, error) {
				req := args[0].(*RefundOrderRequest)
				res, err := handler.(OrderRefundServiceHandler).RefundOrder(ctx, req)
				if err != nil {
					return nil, err
				}
				return triple_protocol.NewResponse(res), nil
			},
		},
	},
}
