// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/zebra-passport/role_path/role_path.proto

package role_path

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RolePath 角色路径关联
type RolePath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PathId        int64                  `protobuf:"varint,3,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDeleted     int32                  `protobuf:"varint,6,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePath) Reset() {
	*x = RolePath{}
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePath) ProtoMessage() {}

func (x *RolePath) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePath.ProtoReflect.Descriptor instead.
func (*RolePath) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP(), []int{0}
}

func (x *RolePath) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RolePath) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *RolePath) GetPathId() int64 {
	if x != nil {
		return x.PathId
	}
	return 0
}

func (x *RolePath) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *RolePath) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *RolePath) GetIsDeleted() int32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

// CreateRolePathRequest 创建角色路径关联请求
type CreateRolePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PathId        int64                  `protobuf:"varint,2,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRolePathRequest) Reset() {
	*x = CreateRolePathRequest{}
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRolePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRolePathRequest) ProtoMessage() {}

func (x *CreateRolePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRolePathRequest.ProtoReflect.Descriptor instead.
func (*CreateRolePathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRolePathRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CreateRolePathRequest) GetPathId() int64 {
	if x != nil {
		return x.PathId
	}
	return 0
}

// UpdateRolePathRequest 更新角色路径关联请求
type UpdateRolePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleId        int64                  `protobuf:"varint,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PathId        int64                  `protobuf:"varint,3,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRolePathRequest) Reset() {
	*x = UpdateRolePathRequest{}
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRolePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRolePathRequest) ProtoMessage() {}

func (x *UpdateRolePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRolePathRequest.ProtoReflect.Descriptor instead.
func (*UpdateRolePathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateRolePathRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRolePathRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *UpdateRolePathRequest) GetPathId() int64 {
	if x != nil {
		return x.PathId
	}
	return 0
}

// DeleteRolePathRequest 删除角色路径关联请求
type DeleteRolePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRolePathRequest) Reset() {
	*x = DeleteRolePathRequest{}
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRolePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRolePathRequest) ProtoMessage() {}

func (x *DeleteRolePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRolePathRequest.ProtoReflect.Descriptor instead.
func (*DeleteRolePathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRolePathRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetRolePathRequest 获取角色路径关联请求
type GetRolePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePathRequest) Reset() {
	*x = GetRolePathRequest{}
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePathRequest) ProtoMessage() {}

func (x *GetRolePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePathRequest.ProtoReflect.Descriptor instead.
func (*GetRolePathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP(), []int{4}
}

func (x *GetRolePathRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetRolePathResponse 获取角色路径关联响应
type GetRolePathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolePath      *RolePath              `protobuf:"bytes,1,opt,name=role_path,json=rolePath,proto3" json:"role_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePathResponse) Reset() {
	*x = GetRolePathResponse{}
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePathResponse) ProtoMessage() {}

func (x *GetRolePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePathResponse.ProtoReflect.Descriptor instead.
func (*GetRolePathResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP(), []int{5}
}

func (x *GetRolePathResponse) GetRolePath() *RolePath {
	if x != nil {
		return x.RolePath
	}
	return nil
}

// ListRolePathRequest 列出角色路径关联请求
type ListRolePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	RoleId        int64                  `protobuf:"varint,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PathId        int64                  `protobuf:"varint,4,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolePathRequest) Reset() {
	*x = ListRolePathRequest{}
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolePathRequest) ProtoMessage() {}

func (x *ListRolePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolePathRequest.ProtoReflect.Descriptor instead.
func (*ListRolePathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP(), []int{6}
}

func (x *ListRolePathRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolePathRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRolePathRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ListRolePathRequest) GetPathId() int64 {
	if x != nil {
		return x.PathId
	}
	return 0
}

// ListRolePathResponse 列出角色路径关联响应
type ListRolePathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolePaths     []*RolePath            `protobuf:"bytes,1,rep,name=role_paths,json=rolePaths,proto3" json:"role_paths,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolePathResponse) Reset() {
	*x = ListRolePathResponse{}
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolePathResponse) ProtoMessage() {}

func (x *ListRolePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolePathResponse.ProtoReflect.Descriptor instead.
func (*ListRolePathResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP(), []int{7}
}

func (x *ListRolePathResponse) GetRolePaths() []*RolePath {
	if x != nil {
		return x.RolePaths
	}
	return nil
}

func (x *ListRolePathResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// BatchCreateRolePathRequest 批量创建角色路径关联请求
type BatchCreateRolePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PathIds       []int64                `protobuf:"varint,2,rep,packed,name=path_ids,json=pathIds,proto3" json:"path_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCreateRolePathRequest) Reset() {
	*x = BatchCreateRolePathRequest{}
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCreateRolePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCreateRolePathRequest) ProtoMessage() {}

func (x *BatchCreateRolePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCreateRolePathRequest.ProtoReflect.Descriptor instead.
func (*BatchCreateRolePathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCreateRolePathRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *BatchCreateRolePathRequest) GetPathIds() []int64 {
	if x != nil {
		return x.PathIds
	}
	return nil
}

// BatchDeleteRolePathRequest 批量删除角色路径关联请求
type BatchDeleteRolePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        int64                  `protobuf:"varint,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PathIds       []int64                `protobuf:"varint,2,rep,packed,name=path_ids,json=pathIds,proto3" json:"path_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteRolePathRequest) Reset() {
	*x = BatchDeleteRolePathRequest{}
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteRolePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteRolePathRequest) ProtoMessage() {}

func (x *BatchDeleteRolePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_role_path_role_path_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteRolePathRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteRolePathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP(), []int{9}
}

func (x *BatchDeleteRolePathRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *BatchDeleteRolePathRequest) GetPathIds() []int64 {
	if x != nil {
		return x.PathIds
	}
	return nil
}

var File_api_zebra_passport_role_path_role_path_proto protoreflect.FileDescriptor

const file_api_zebra_passport_role_path_role_path_proto_rawDesc = "" +
	"\n" +
	",api/zebra-passport/role_path/role_path.proto\x12\trole_path\"\xad\x01\n" +
	"\bRolePath\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\x12\x17\n" +
	"\apath_id\x18\x03 \x01(\x03R\x06pathId\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x05 \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x06 \x01(\x05R\tisDeleted\"I\n" +
	"\x15CreateRolePathRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x17\n" +
	"\apath_id\x18\x02 \x01(\x03R\x06pathId\"Y\n" +
	"\x15UpdateRolePathRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\x03R\x06roleId\x12\x17\n" +
	"\apath_id\x18\x03 \x01(\x03R\x06pathId\"'\n" +
	"\x15DeleteRolePathRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"$\n" +
	"\x12GetRolePathRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"G\n" +
	"\x13GetRolePathResponse\x120\n" +
	"\trole_path\x18\x01 \x01(\v2\x13.role_path.RolePathR\brolePath\"x\n" +
	"\x13ListRolePathRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\x03R\x06roleId\x12\x17\n" +
	"\apath_id\x18\x04 \x01(\x03R\x06pathId\"`\n" +
	"\x14ListRolePathResponse\x122\n" +
	"\n" +
	"role_paths\x18\x01 \x03(\v2\x13.role_path.RolePathR\trolePaths\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"P\n" +
	"\x1aBatchCreateRolePathRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x19\n" +
	"\bpath_ids\x18\x02 \x03(\x03R\apathIds\"P\n" +
	"\x1aBatchDeleteRolePathRequest\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\x03R\x06roleId\x12\x19\n" +
	"\bpath_ids\x18\x02 \x03(\x03R\apathIds2\x91\x04\n" +
	"\x0fRolePathService\x12?\n" +
	"\x06Create\x12 .role_path.CreateRolePathRequest\x1a\x13.role_path.RolePath\x12?\n" +
	"\x06Update\x12 .role_path.UpdateRolePathRequest\x1a\x13.role_path.RolePath\x12?\n" +
	"\x06Delete\x12 .role_path.DeleteRolePathRequest\x1a\x13.role_path.RolePath\x12D\n" +
	"\x03Get\x12\x1d.role_path.GetRolePathRequest\x1a\x1e.role_path.GetRolePathResponse\x12G\n" +
	"\x04List\x12\x1e.role_path.ListRolePathRequest\x1a\x1f.role_path.ListRolePathResponse\x12U\n" +
	"\vBatchCreate\x12%.role_path.BatchCreateRolePathRequest\x1a\x1f.role_path.ListRolePathResponse\x12U\n" +
	"\vBatchDelete\x12%.role_path.BatchDeleteRolePathRequest\x1a\x1f.role_path.ListRolePathResponseB*Z(./api/zebra-passport/role_path;role_pathb\x06proto3"

var (
	file_api_zebra_passport_role_path_role_path_proto_rawDescOnce sync.Once
	file_api_zebra_passport_role_path_role_path_proto_rawDescData []byte
)

func file_api_zebra_passport_role_path_role_path_proto_rawDescGZIP() []byte {
	file_api_zebra_passport_role_path_role_path_proto_rawDescOnce.Do(func() {
		file_api_zebra_passport_role_path_role_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zebra_passport_role_path_role_path_proto_rawDesc), len(file_api_zebra_passport_role_path_role_path_proto_rawDesc)))
	})
	return file_api_zebra_passport_role_path_role_path_proto_rawDescData
}

var file_api_zebra_passport_role_path_role_path_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_zebra_passport_role_path_role_path_proto_goTypes = []any{
	(*RolePath)(nil),                   // 0: role_path.RolePath
	(*CreateRolePathRequest)(nil),      // 1: role_path.CreateRolePathRequest
	(*UpdateRolePathRequest)(nil),      // 2: role_path.UpdateRolePathRequest
	(*DeleteRolePathRequest)(nil),      // 3: role_path.DeleteRolePathRequest
	(*GetRolePathRequest)(nil),         // 4: role_path.GetRolePathRequest
	(*GetRolePathResponse)(nil),        // 5: role_path.GetRolePathResponse
	(*ListRolePathRequest)(nil),        // 6: role_path.ListRolePathRequest
	(*ListRolePathResponse)(nil),       // 7: role_path.ListRolePathResponse
	(*BatchCreateRolePathRequest)(nil), // 8: role_path.BatchCreateRolePathRequest
	(*BatchDeleteRolePathRequest)(nil), // 9: role_path.BatchDeleteRolePathRequest
}
var file_api_zebra_passport_role_path_role_path_proto_depIdxs = []int32{
	0, // 0: role_path.GetRolePathResponse.role_path:type_name -> role_path.RolePath
	0, // 1: role_path.ListRolePathResponse.role_paths:type_name -> role_path.RolePath
	1, // 2: role_path.RolePathService.Create:input_type -> role_path.CreateRolePathRequest
	2, // 3: role_path.RolePathService.Update:input_type -> role_path.UpdateRolePathRequest
	3, // 4: role_path.RolePathService.Delete:input_type -> role_path.DeleteRolePathRequest
	4, // 5: role_path.RolePathService.Get:input_type -> role_path.GetRolePathRequest
	6, // 6: role_path.RolePathService.List:input_type -> role_path.ListRolePathRequest
	8, // 7: role_path.RolePathService.BatchCreate:input_type -> role_path.BatchCreateRolePathRequest
	9, // 8: role_path.RolePathService.BatchDelete:input_type -> role_path.BatchDeleteRolePathRequest
	0, // 9: role_path.RolePathService.Create:output_type -> role_path.RolePath
	0, // 10: role_path.RolePathService.Update:output_type -> role_path.RolePath
	0, // 11: role_path.RolePathService.Delete:output_type -> role_path.RolePath
	5, // 12: role_path.RolePathService.Get:output_type -> role_path.GetRolePathResponse
	7, // 13: role_path.RolePathService.List:output_type -> role_path.ListRolePathResponse
	7, // 14: role_path.RolePathService.BatchCreate:output_type -> role_path.ListRolePathResponse
	7, // 15: role_path.RolePathService.BatchDelete:output_type -> role_path.ListRolePathResponse
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_zebra_passport_role_path_role_path_proto_init() }
func file_api_zebra_passport_role_path_role_path_proto_init() {
	if File_api_zebra_passport_role_path_role_path_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zebra_passport_role_path_role_path_proto_rawDesc), len(file_api_zebra_passport_role_path_role_path_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zebra_passport_role_path_role_path_proto_goTypes,
		DependencyIndexes: file_api_zebra_passport_role_path_role_path_proto_depIdxs,
		MessageInfos:      file_api_zebra_passport_role_path_role_path_proto_msgTypes,
	}.Build()
	File_api_zebra_passport_role_path_role_path_proto = out.File
	file_api_zebra_passport_role_path_role_path_proto_goTypes = nil
	file_api_zebra_passport_role_path_role_path_proto_depIdxs = nil
}
