// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/zebra-passport/captcha/captcha.proto

package captcha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取验证码请求（空请求）
type GetCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptchaRequest) Reset() {
	*x = GetCaptchaRequest{}
	mi := &file_api_zebra_passport_captcha_captcha_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptchaRequest) ProtoMessage() {}

func (x *GetCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_captcha_captcha_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptchaRequest.ProtoReflect.Descriptor instead.
func (*GetCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_captcha_captcha_proto_rawDescGZIP(), []int{0}
}

// 验证码响应
type CaptchaResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码: 0=成功, -1=失败
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	CaptchaEnabled bool                   `protobuf:"varint,3,opt,name=captcha_enabled,json=captchaEnabled,proto3" json:"captcha_enabled,omitempty"` // 验证码开关
	Uuid           string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`                                            // 验证码唯一标识
	Img            string                 `protobuf:"bytes,5,opt,name=img,proto3" json:"img,omitempty"`                                              // base64 编码的验证码图片
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CaptchaResponse) Reset() {
	*x = CaptchaResponse{}
	mi := &file_api_zebra_passport_captcha_captcha_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptchaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptchaResponse) ProtoMessage() {}

func (x *CaptchaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_captcha_captcha_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptchaResponse.ProtoReflect.Descriptor instead.
func (*CaptchaResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_captcha_captcha_proto_rawDescGZIP(), []int{1}
}

func (x *CaptchaResponse) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *CaptchaResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CaptchaResponse) GetCaptchaEnabled() bool {
	if x != nil {
		return x.CaptchaEnabled
	}
	return false
}

func (x *CaptchaResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CaptchaResponse) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

// 校验验证码请求
type CheckCaptchaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckCaptchaRequest) Reset() {
	*x = CheckCaptchaRequest{}
	mi := &file_api_zebra_passport_captcha_captcha_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckCaptchaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCaptchaRequest) ProtoMessage() {}

func (x *CheckCaptchaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_captcha_captcha_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCaptchaRequest.ProtoReflect.Descriptor instead.
func (*CheckCaptchaRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_captcha_captcha_proto_rawDescGZIP(), []int{2}
}

func (x *CheckCaptchaRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CheckCaptchaRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 通用响应
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_zebra_passport_captcha_captcha_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_captcha_captcha_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_captcha_captcha_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_zebra_passport_captcha_captcha_proto protoreflect.FileDescriptor

const file_api_zebra_passport_captcha_captcha_proto_rawDesc = "" +
	"\n" +
	"(api/zebra-passport/captcha/captcha.proto\x12\acaptcha\x1a\x1egoogle/protobuf/wrappers.proto\"\x13\n" +
	"\x11GetCaptchaRequest\"\xa3\x01\n" +
	"\x0fCaptchaResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x0fcaptcha_enabled\x18\x03 \x01(\bR\x0ecaptchaEnabled\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03img\x18\x05 \x01(\tR\x03img\"=\n" +
	"\x13CheckCaptchaRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\"M\n" +
	"\bResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\x95\x01\n" +
	"\x0eCaptchaService\x12B\n" +
	"\n" +
	"GetCaptcha\x12\x1a.captcha.GetCaptchaRequest\x1a\x18.captcha.CaptchaResponse\x12?\n" +
	"\fCheckCaptcha\x12\x1c.captcha.CheckCaptchaRequest\x1a\x11.captcha.ResponseB&Z$./api/zebra-passport/captcha;captchab\x06proto3"

var (
	file_api_zebra_passport_captcha_captcha_proto_rawDescOnce sync.Once
	file_api_zebra_passport_captcha_captcha_proto_rawDescData []byte
)

func file_api_zebra_passport_captcha_captcha_proto_rawDescGZIP() []byte {
	file_api_zebra_passport_captcha_captcha_proto_rawDescOnce.Do(func() {
		file_api_zebra_passport_captcha_captcha_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zebra_passport_captcha_captcha_proto_rawDesc), len(file_api_zebra_passport_captcha_captcha_proto_rawDesc)))
	})
	return file_api_zebra_passport_captcha_captcha_proto_rawDescData
}

var file_api_zebra_passport_captcha_captcha_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_zebra_passport_captcha_captcha_proto_goTypes = []any{
	(*GetCaptchaRequest)(nil),     // 0: captcha.GetCaptchaRequest
	(*CaptchaResponse)(nil),       // 1: captcha.CaptchaResponse
	(*CheckCaptchaRequest)(nil),   // 2: captcha.CheckCaptchaRequest
	(*Response)(nil),              // 3: captcha.Response
	(*wrapperspb.Int32Value)(nil), // 4: google.protobuf.Int32Value
}
var file_api_zebra_passport_captcha_captcha_proto_depIdxs = []int32{
	4, // 0: captcha.CaptchaResponse.code:type_name -> google.protobuf.Int32Value
	4, // 1: captcha.Response.code:type_name -> google.protobuf.Int32Value
	0, // 2: captcha.CaptchaService.GetCaptcha:input_type -> captcha.GetCaptchaRequest
	2, // 3: captcha.CaptchaService.CheckCaptcha:input_type -> captcha.CheckCaptchaRequest
	1, // 4: captcha.CaptchaService.GetCaptcha:output_type -> captcha.CaptchaResponse
	3, // 5: captcha.CaptchaService.CheckCaptcha:output_type -> captcha.Response
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_zebra_passport_captcha_captcha_proto_init() }
func file_api_zebra_passport_captcha_captcha_proto_init() {
	if File_api_zebra_passport_captcha_captcha_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zebra_passport_captcha_captcha_proto_rawDesc), len(file_api_zebra_passport_captcha_captcha_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zebra_passport_captcha_captcha_proto_goTypes,
		DependencyIndexes: file_api_zebra_passport_captcha_captcha_proto_depIdxs,
		MessageInfos:      file_api_zebra_passport_captcha_captcha_proto_msgTypes,
	}.Build()
	File_api_zebra_passport_captcha_captcha_proto = out.File
	file_api_zebra_passport_captcha_captcha_proto_goTypes = nil
	file_api_zebra_passport_captcha_captcha_proto_depIdxs = nil
}
