//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/zebra-message/weixin/weixin.proto

package weixin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 微信模板
type WeixinTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TplId         int64                  `protobuf:"varint,1,opt,name=tpl_id,json=tplId,proto3" json:"tpl_id,omitempty"`
	TplCode       string                 `protobuf:"bytes,2,opt,name=tpl_code,json=tplCode,proto3" json:"tpl_code,omitempty"`
	TplName       string                 `protobuf:"bytes,3,opt,name=tpl_name,json=tplName,proto3" json:"tpl_name,omitempty"`
	TplIdWeixin   string                 `protobuf:"bytes,4,opt,name=tpl_id_weixin,json=tplIdWeixin,proto3" json:"tpl_id_weixin,omitempty"` // 微信模板ID
	TplStatus     int32                  `protobuf:"varint,5,opt,name=tpl_status,json=tplStatus,proto3" json:"tpl_status,omitempty"`        // 0=禁用, 1=启用
	CreateTime    int64                  `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDeleted     int32                  `protobuf:"varint,8,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeixinTemplate) Reset() {
	*x = WeixinTemplate{}
	mi := &file_api_zebra_message_weixin_weixin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeixinTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeixinTemplate) ProtoMessage() {}

func (x *WeixinTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_message_weixin_weixin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeixinTemplate.ProtoReflect.Descriptor instead.
func (*WeixinTemplate) Descriptor() ([]byte, []int) {
	return file_api_zebra_message_weixin_weixin_proto_rawDescGZIP(), []int{0}
}

func (x *WeixinTemplate) GetTplId() int64 {
	if x != nil {
		return x.TplId
	}
	return 0
}

func (x *WeixinTemplate) GetTplCode() string {
	if x != nil {
		return x.TplCode
	}
	return ""
}

func (x *WeixinTemplate) GetTplName() string {
	if x != nil {
		return x.TplName
	}
	return ""
}

func (x *WeixinTemplate) GetTplIdWeixin() string {
	if x != nil {
		return x.TplIdWeixin
	}
	return ""
}

func (x *WeixinTemplate) GetTplStatus() int32 {
	if x != nil {
		return x.TplStatus
	}
	return 0
}

func (x *WeixinTemplate) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *WeixinTemplate) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *WeixinTemplate) GetIsDeleted() int32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

// 发送微信消息请求
type SendWeixinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	TplCode       string                 `protobuf:"bytes,2,opt,name=tpl_code,json=tplCode,proto3" json:"tpl_code,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Page          string                 `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"` // 小程序页面路径
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWeixinRequest) Reset() {
	*x = SendWeixinRequest{}
	mi := &file_api_zebra_message_weixin_weixin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWeixinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWeixinRequest) ProtoMessage() {}

func (x *SendWeixinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_message_weixin_weixin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWeixinRequest.ProtoReflect.Descriptor instead.
func (*SendWeixinRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_message_weixin_weixin_proto_rawDescGZIP(), []int{1}
}

func (x *SendWeixinRequest) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *SendWeixinRequest) GetTplCode() string {
	if x != nil {
		return x.TplCode
	}
	return ""
}

func (x *SendWeixinRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendWeixinRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

// 发送微信消息响应
type SendWeixinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MsgId         string                 `protobuf:"bytes,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendWeixinResponse) Reset() {
	*x = SendWeixinResponse{}
	mi := &file_api_zebra_message_weixin_weixin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendWeixinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendWeixinResponse) ProtoMessage() {}

func (x *SendWeixinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_message_weixin_weixin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendWeixinResponse.ProtoReflect.Descriptor instead.
func (*SendWeixinResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_message_weixin_weixin_proto_rawDescGZIP(), []int{2}
}

func (x *SendWeixinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendWeixinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendWeixinResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

// 批量发送微信消息请求
type BatchSendWeixinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openids       []string               `protobuf:"bytes,1,rep,name=openids,proto3" json:"openids,omitempty"`
	TplCode       string                 `protobuf:"bytes,2,opt,name=tpl_code,json=tplCode,proto3" json:"tpl_code,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Page          string                 `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendWeixinRequest) Reset() {
	*x = BatchSendWeixinRequest{}
	mi := &file_api_zebra_message_weixin_weixin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendWeixinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendWeixinRequest) ProtoMessage() {}

func (x *BatchSendWeixinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_message_weixin_weixin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendWeixinRequest.ProtoReflect.Descriptor instead.
func (*BatchSendWeixinRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_message_weixin_weixin_proto_rawDescGZIP(), []int{3}
}

func (x *BatchSendWeixinRequest) GetOpenids() []string {
	if x != nil {
		return x.Openids
	}
	return nil
}

func (x *BatchSendWeixinRequest) GetTplCode() string {
	if x != nil {
		return x.TplCode
	}
	return ""
}

func (x *BatchSendWeixinRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BatchSendWeixinRequest) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

// 批量发送微信消息响应
type BatchSendWeixinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MsgIds        []string               `protobuf:"bytes,3,rep,name=msg_ids,json=msgIds,proto3" json:"msg_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchSendWeixinResponse) Reset() {
	*x = BatchSendWeixinResponse{}
	mi := &file_api_zebra_message_weixin_weixin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSendWeixinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSendWeixinResponse) ProtoMessage() {}

func (x *BatchSendWeixinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_message_weixin_weixin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSendWeixinResponse.ProtoReflect.Descriptor instead.
func (*BatchSendWeixinResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_message_weixin_weixin_proto_rawDescGZIP(), []int{4}
}

func (x *BatchSendWeixinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchSendWeixinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchSendWeixinResponse) GetMsgIds() []string {
	if x != nil {
		return x.MsgIds
	}
	return nil
}

var File_api_zebra_message_weixin_weixin_proto protoreflect.FileDescriptor

const file_api_zebra_message_weixin_weixin_proto_rawDesc = "" +
	"\n" +
	"%api/zebra-message/weixin/weixin.proto\x12\x06weixin\"\x81\x02\n" +
	"\x0eWeixinTemplate\x12\x15\n" +
	"\x06tpl_id\x18\x01 \x01(\x03R\x05tplId\x12\x19\n" +
	"\btpl_code\x18\x02 \x01(\tR\atplCode\x12\x19\n" +
	"\btpl_name\x18\x03 \x01(\tR\atplName\x12\"\n" +
	"\rtpl_id_weixin\x18\x04 \x01(\tR\vtplIdWeixin\x12\x1d\n" +
	"\n" +
	"tpl_status\x18\x05 \x01(\x05R\ttplStatus\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\a \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\b \x01(\x05R\tisDeleted\"\xcc\x01\n" +
	"\x11SendWeixinRequest\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\x12\x19\n" +
	"\btpl_code\x18\x02 \x01(\tR\atplCode\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.weixin.SendWeixinRequest.DataEntryR\x04data\x12\x12\n" +
	"\x04page\x18\x04 \x01(\tR\x04page\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x12SendWeixinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\tR\x05msgId\"\xd8\x01\n" +
	"\x16BatchSendWeixinRequest\x12\x18\n" +
	"\aopenids\x18\x01 \x03(\tR\aopenids\x12\x19\n" +
	"\btpl_code\x18\x02 \x01(\tR\atplCode\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.weixin.BatchSendWeixinRequest.DataEntryR\x04data\x12\x12\n" +
	"\x04page\x18\x04 \x01(\tR\x04page\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"f\n" +
	"\x17BatchSendWeixinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\amsg_ids\x18\x03 \x03(\tR\x06msgIds2\xa8\x01\n" +
	"\rWeixinService\x12C\n" +
	"\n" +
	"SendWeixin\x12\x19.weixin.SendWeixinRequest\x1a\x1a.weixin.SendWeixinResponse\x12R\n" +
	"\x0fBatchSendWeixin\x12\x1e.weixin.BatchSendWeixinRequest\x1a\x1f.weixin.BatchSendWeixinResponseBFZD./github.com/21bigticket/zebra-proto/api/zebra-message/weixin;weixinb\x06proto3"

var (
	file_api_zebra_message_weixin_weixin_proto_rawDescOnce sync.Once
	file_api_zebra_message_weixin_weixin_proto_rawDescData []byte
)

func file_api_zebra_message_weixin_weixin_proto_rawDescGZIP() []byte {
	file_api_zebra_message_weixin_weixin_proto_rawDescOnce.Do(func() {
		file_api_zebra_message_weixin_weixin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zebra_message_weixin_weixin_proto_rawDesc), len(file_api_zebra_message_weixin_weixin_proto_rawDesc)))
	})
	return file_api_zebra_message_weixin_weixin_proto_rawDescData
}

var file_api_zebra_message_weixin_weixin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_zebra_message_weixin_weixin_proto_goTypes = []any{
	(*WeixinTemplate)(nil),          // 0: weixin.WeixinTemplate
	(*SendWeixinRequest)(nil),       // 1: weixin.SendWeixinRequest
	(*SendWeixinResponse)(nil),      // 2: weixin.SendWeixinResponse
	(*BatchSendWeixinRequest)(nil),  // 3: weixin.BatchSendWeixinRequest
	(*BatchSendWeixinResponse)(nil), // 4: weixin.BatchSendWeixinResponse
	nil,                             // 5: weixin.SendWeixinRequest.DataEntry
	nil,                             // 6: weixin.BatchSendWeixinRequest.DataEntry
}
var file_api_zebra_message_weixin_weixin_proto_depIdxs = []int32{
	5, // 0: weixin.SendWeixinRequest.data:type_name -> weixin.SendWeixinRequest.DataEntry
	6, // 1: weixin.BatchSendWeixinRequest.data:type_name -> weixin.BatchSendWeixinRequest.DataEntry
	1, // 2: weixin.WeixinService.SendWeixin:input_type -> weixin.SendWeixinRequest
	3, // 3: weixin.WeixinService.BatchSendWeixin:input_type -> weixin.BatchSendWeixinRequest
	2, // 4: weixin.WeixinService.SendWeixin:output_type -> weixin.SendWeixinResponse
	4, // 5: weixin.WeixinService.BatchSendWeixin:output_type -> weixin.BatchSendWeixinResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_zebra_message_weixin_weixin_proto_init() }
func file_api_zebra_message_weixin_weixin_proto_init() {
	if File_api_zebra_message_weixin_weixin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zebra_message_weixin_weixin_proto_rawDesc), len(file_api_zebra_message_weixin_weixin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zebra_message_weixin_weixin_proto_goTypes,
		DependencyIndexes: file_api_zebra_message_weixin_weixin_proto_depIdxs,
		MessageInfos:      file_api_zebra_message_weixin_weixin_proto_msgTypes,
	}.Build()
	File_api_zebra_message_weixin_weixin_proto = out.File
	file_api_zebra_message_weixin_weixin_proto_goTypes = nil
	file_api_zebra_message_weixin_weixin_proto_depIdxs = nil
}
