// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/zebra-passport/dict_type/dict_type.proto

package dict_type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 字典类型（对应 sys_dict_type 表）
type DictType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        int64                  `protobuf:"varint,1,opt,name=dict_id,json=dictId,proto3" json:"dict_id,omitempty"`
	DictName      string                 `protobuf:"bytes,2,opt,name=dict_name,json=dictName,proto3" json:"dict_name,omitempty"`
	DictType      string                 `protobuf:"bytes,3,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // 状态（0正常 1停用）
	CreateBy      string                 `protobuf:"bytes,5,opt,name=create_by,json=createBy,proto3" json:"create_by,omitempty"`
	CreateTime    int64                  `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateBy      string                 `protobuf:"bytes,7,opt,name=update_by,json=updateBy,proto3" json:"update_by,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Remark        string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictType) Reset() {
	*x = DictType{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictType) ProtoMessage() {}

func (x *DictType) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictType.ProtoReflect.Descriptor instead.
func (*DictType) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{0}
}

func (x *DictType) GetDictId() int64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

func (x *DictType) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *DictType) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *DictType) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DictType) GetCreateBy() string {
	if x != nil {
		return x.CreateBy
	}
	return ""
}

func (x *DictType) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *DictType) GetUpdateBy() string {
	if x != nil {
		return x.UpdateBy
	}
	return ""
}

func (x *DictType) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *DictType) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 列出字典类型请求
type ListDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	DictName      string                 `protobuf:"bytes,3,opt,name=dict_name,json=dictName,proto3" json:"dict_name,omitempty"`
	DictType      string                 `protobuf:"bytes,4,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	BeginTime     string                 `protobuf:"bytes,6,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictTypeRequest) Reset() {
	*x = ListDictTypeRequest{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictTypeRequest) ProtoMessage() {}

func (x *ListDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictTypeRequest.ProtoReflect.Descriptor instead.
func (*ListDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{1}
}

func (x *ListDictTypeRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDictTypeRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDictTypeRequest) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *ListDictTypeRequest) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *ListDictTypeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListDictTypeRequest) GetBeginTime() string {
	if x != nil {
		return x.BeginTime
	}
	return ""
}

func (x *ListDictTypeRequest) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

// 列出字典类型响应
type ListDictTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码: 0=成功, -1=失败, -2=数据为空
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	DictTypes     []*DictType            `protobuf:"bytes,3,rep,name=dict_types,json=dictTypes,proto3" json:"dict_types,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDictTypeResponse) Reset() {
	*x = ListDictTypeResponse{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDictTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDictTypeResponse) ProtoMessage() {}

func (x *ListDictTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDictTypeResponse.ProtoReflect.Descriptor instead.
func (*ListDictTypeResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{2}
}

func (x *ListDictTypeResponse) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *ListDictTypeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListDictTypeResponse) GetDictTypes() []*DictType {
	if x != nil {
		return x.DictTypes
	}
	return nil
}

func (x *ListDictTypeResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取字典类型请求
type GetDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        int64                  `protobuf:"varint,1,opt,name=dict_id,json=dictId,proto3" json:"dict_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDictTypeRequest) Reset() {
	*x = GetDictTypeRequest{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictTypeRequest) ProtoMessage() {}

func (x *GetDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictTypeRequest.ProtoReflect.Descriptor instead.
func (*GetDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{3}
}

func (x *GetDictTypeRequest) GetDictId() int64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

// 获取字典类型响应
type GetDictTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码: 0=成功, -1=失败, -2=数据为空
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	DictType      *DictType              `protobuf:"bytes,3,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDictTypeResponse) Reset() {
	*x = GetDictTypeResponse{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDictTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDictTypeResponse) ProtoMessage() {}

func (x *GetDictTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDictTypeResponse.ProtoReflect.Descriptor instead.
func (*GetDictTypeResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{4}
}

func (x *GetDictTypeResponse) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *GetDictTypeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetDictTypeResponse) GetDictType() *DictType {
	if x != nil {
		return x.DictType
	}
	return nil
}

// 创建字典类型请求
type CreateDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictName      string                 `protobuf:"bytes,1,opt,name=dict_name,json=dictName,proto3" json:"dict_name,omitempty"`
	DictType      string                 `protobuf:"bytes,2,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDictTypeRequest) Reset() {
	*x = CreateDictTypeRequest{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDictTypeRequest) ProtoMessage() {}

func (x *CreateDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDictTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDictTypeRequest) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *CreateDictTypeRequest) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

func (x *CreateDictTypeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateDictTypeRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 更新字典类型请求
type UpdateDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        int64                  `protobuf:"varint,1,opt,name=dict_id,json=dictId,proto3" json:"dict_id,omitempty"`
	DictName      *string                `protobuf:"bytes,2,opt,name=dict_name,json=dictName,proto3,oneof" json:"dict_name,omitempty"`
	DictType      *string                `protobuf:"bytes,3,opt,name=dict_type,json=dictType,proto3,oneof" json:"dict_type,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Remark        *string                `protobuf:"bytes,5,opt,name=remark,proto3,oneof" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDictTypeRequest) Reset() {
	*x = UpdateDictTypeRequest{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDictTypeRequest) ProtoMessage() {}

func (x *UpdateDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDictTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDictTypeRequest) GetDictId() int64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

func (x *UpdateDictTypeRequest) GetDictName() string {
	if x != nil && x.DictName != nil {
		return *x.DictName
	}
	return ""
}

func (x *UpdateDictTypeRequest) GetDictType() string {
	if x != nil && x.DictType != nil {
		return *x.DictType
	}
	return ""
}

func (x *UpdateDictTypeRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *UpdateDictTypeRequest) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

// 删除字典类型请求
type DeleteDictTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictIds       []int64                `protobuf:"varint,1,rep,packed,name=dict_ids,json=dictIds,proto3" json:"dict_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDictTypeRequest) Reset() {
	*x = DeleteDictTypeRequest{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDictTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDictTypeRequest) ProtoMessage() {}

func (x *DeleteDictTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDictTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteDictTypeRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDictTypeRequest) GetDictIds() []int64 {
	if x != nil {
		return x.DictIds
	}
	return nil
}

// 字典类型选项（用于下拉选择）
type DictTypeOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DictId        int64                  `protobuf:"varint,1,opt,name=dict_id,json=dictId,proto3" json:"dict_id,omitempty"`
	DictName      string                 `protobuf:"bytes,2,opt,name=dict_name,json=dictName,proto3" json:"dict_name,omitempty"`
	DictType      string                 `protobuf:"bytes,3,opt,name=dict_type,json=dictType,proto3" json:"dict_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DictTypeOption) Reset() {
	*x = DictTypeOption{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DictTypeOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictTypeOption) ProtoMessage() {}

func (x *DictTypeOption) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictTypeOption.ProtoReflect.Descriptor instead.
func (*DictTypeOption) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{8}
}

func (x *DictTypeOption) GetDictId() int64 {
	if x != nil {
		return x.DictId
	}
	return 0
}

func (x *DictTypeOption) GetDictName() string {
	if x != nil {
		return x.DictName
	}
	return ""
}

func (x *DictTypeOption) GetDictType() string {
	if x != nil {
		return x.DictType
	}
	return ""
}

// 选项列表响应
type OptionSelectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码: 0=成功, -1=失败, -2=数据为空
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	DictTypes     []*DictTypeOption      `protobuf:"bytes,3,rep,name=dict_types,json=dictTypes,proto3" json:"dict_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionSelectResponse) Reset() {
	*x = OptionSelectResponse{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionSelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionSelectResponse) ProtoMessage() {}

func (x *OptionSelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionSelectResponse.ProtoReflect.Descriptor instead.
func (*OptionSelectResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{9}
}

func (x *OptionSelectResponse) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *OptionSelectResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OptionSelectResponse) GetDictTypes() []*DictTypeOption {
	if x != nil {
		return x.DictTypes
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *wrapperspb.Int32Value `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 业务状态码: 0=成功, -1=失败, -2=数据为空
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP(), []int{10}
}

func (x *Response) GetCode() *wrapperspb.Int32Value {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_zebra_passport_dict_type_dict_type_proto protoreflect.FileDescriptor

const file_api_zebra_passport_dict_type_dict_type_proto_rawDesc = "" +
	"\n" +
	",api/zebra-passport/dict_type/dict_type.proto\x12\tdict_type\x1a\x1egoogle/protobuf/wrappers.proto\"\x89\x02\n" +
	"\bDictType\x12\x17\n" +
	"\adict_id\x18\x01 \x01(\x03R\x06dictId\x12\x1b\n" +
	"\tdict_name\x18\x02 \x01(\tR\bdictName\x12\x1b\n" +
	"\tdict_type\x18\x03 \x01(\tR\bdictType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1b\n" +
	"\tcreate_by\x18\x05 \x01(\tR\bcreateBy\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x03R\n" +
	"createTime\x12\x1b\n" +
	"\tupdate_by\x18\a \x01(\tR\bupdateBy\x12\x1f\n" +
	"\vupdate_time\x18\b \x01(\x03R\n" +
	"updateTime\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\"\xd2\x01\n" +
	"\x13ListDictTypeRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tdict_name\x18\x03 \x01(\tR\bdictName\x12\x1b\n" +
	"\tdict_type\x18\x04 \x01(\tR\bdictType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"begin_time\x18\x06 \x01(\tR\tbeginTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\"\xa3\x01\n" +
	"\x14ListDictTypeResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x122\n" +
	"\n" +
	"dict_types\x18\x03 \x03(\v2\x13.dict_type.DictTypeR\tdictTypes\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"-\n" +
	"\x12GetDictTypeRequest\x12\x17\n" +
	"\adict_id\x18\x01 \x01(\x03R\x06dictId\"\x8a\x01\n" +
	"\x13GetDictTypeResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x120\n" +
	"\tdict_type\x18\x03 \x01(\v2\x13.dict_type.DictTypeR\bdictType\"\x81\x01\n" +
	"\x15CreateDictTypeRequest\x12\x1b\n" +
	"\tdict_name\x18\x01 \x01(\tR\bdictName\x12\x1b\n" +
	"\tdict_type\x18\x02 \x01(\tR\bdictType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\"\xe0\x01\n" +
	"\x15UpdateDictTypeRequest\x12\x17\n" +
	"\adict_id\x18\x01 \x01(\x03R\x06dictId\x12 \n" +
	"\tdict_name\x18\x02 \x01(\tH\x00R\bdictName\x88\x01\x01\x12 \n" +
	"\tdict_type\x18\x03 \x01(\tH\x01R\bdictType\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x02R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06remark\x18\x05 \x01(\tH\x03R\x06remark\x88\x01\x01B\f\n" +
	"\n" +
	"_dict_nameB\f\n" +
	"\n" +
	"_dict_typeB\t\n" +
	"\a_statusB\t\n" +
	"\a_remark\"2\n" +
	"\x15DeleteDictTypeRequest\x12\x19\n" +
	"\bdict_ids\x18\x01 \x03(\x03R\adictIds\"c\n" +
	"\x0eDictTypeOption\x12\x17\n" +
	"\adict_id\x18\x01 \x01(\x03R\x06dictId\x12\x1b\n" +
	"\tdict_name\x18\x02 \x01(\tR\bdictName\x12\x1b\n" +
	"\tdict_type\x18\x03 \x01(\tR\bdictType\"\x93\x01\n" +
	"\x14OptionSelectResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x128\n" +
	"\n" +
	"dict_types\x18\x03 \x03(\v2\x19.dict_type.DictTypeOptionR\tdictTypes\"M\n" +
	"\bResponse\x12/\n" +
	"\x04code\x18\x01 \x01(\v2\x1b.google.protobuf.Int32ValueR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\xf7\x03\n" +
	"\x0fDictTypeService\x12G\n" +
	"\x04List\x12\x1e.dict_type.ListDictTypeRequest\x1a\x1f.dict_type.ListDictTypeResponse\x12D\n" +
	"\x03Get\x12\x1d.dict_type.GetDictTypeRequest\x1a\x1e.dict_type.GetDictTypeResponse\x12?\n" +
	"\x06Create\x12 .dict_type.CreateDictTypeRequest\x1a\x13.dict_type.Response\x12?\n" +
	"\x06Update\x12 .dict_type.UpdateDictTypeRequest\x1a\x13.dict_type.Response\x12?\n" +
	"\x06Delete\x12 .dict_type.DeleteDictTypeRequest\x1a\x13.dict_type.Response\x12B\n" +
	"\fRefreshCache\x12\x1d.dict_type.GetDictTypeRequest\x1a\x13.dict_type.Response\x12N\n" +
	"\fOptionSelect\x12\x1d.dict_type.GetDictTypeRequest\x1a\x1f.dict_type.OptionSelectResponseB*Z(./api/zebra-passport/dict_type;dict_typeb\x06proto3"

var (
	file_api_zebra_passport_dict_type_dict_type_proto_rawDescOnce sync.Once
	file_api_zebra_passport_dict_type_dict_type_proto_rawDescData []byte
)

func file_api_zebra_passport_dict_type_dict_type_proto_rawDescGZIP() []byte {
	file_api_zebra_passport_dict_type_dict_type_proto_rawDescOnce.Do(func() {
		file_api_zebra_passport_dict_type_dict_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zebra_passport_dict_type_dict_type_proto_rawDesc), len(file_api_zebra_passport_dict_type_dict_type_proto_rawDesc)))
	})
	return file_api_zebra_passport_dict_type_dict_type_proto_rawDescData
}

var file_api_zebra_passport_dict_type_dict_type_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_zebra_passport_dict_type_dict_type_proto_goTypes = []any{
	(*DictType)(nil),              // 0: dict_type.DictType
	(*ListDictTypeRequest)(nil),   // 1: dict_type.ListDictTypeRequest
	(*ListDictTypeResponse)(nil),  // 2: dict_type.ListDictTypeResponse
	(*GetDictTypeRequest)(nil),    // 3: dict_type.GetDictTypeRequest
	(*GetDictTypeResponse)(nil),   // 4: dict_type.GetDictTypeResponse
	(*CreateDictTypeRequest)(nil), // 5: dict_type.CreateDictTypeRequest
	(*UpdateDictTypeRequest)(nil), // 6: dict_type.UpdateDictTypeRequest
	(*DeleteDictTypeRequest)(nil), // 7: dict_type.DeleteDictTypeRequest
	(*DictTypeOption)(nil),        // 8: dict_type.DictTypeOption
	(*OptionSelectResponse)(nil),  // 9: dict_type.OptionSelectResponse
	(*Response)(nil),              // 10: dict_type.Response
	(*wrapperspb.Int32Value)(nil), // 11: google.protobuf.Int32Value
}
var file_api_zebra_passport_dict_type_dict_type_proto_depIdxs = []int32{
	11, // 0: dict_type.ListDictTypeResponse.code:type_name -> google.protobuf.Int32Value
	0,  // 1: dict_type.ListDictTypeResponse.dict_types:type_name -> dict_type.DictType
	11, // 2: dict_type.GetDictTypeResponse.code:type_name -> google.protobuf.Int32Value
	0,  // 3: dict_type.GetDictTypeResponse.dict_type:type_name -> dict_type.DictType
	11, // 4: dict_type.OptionSelectResponse.code:type_name -> google.protobuf.Int32Value
	8,  // 5: dict_type.OptionSelectResponse.dict_types:type_name -> dict_type.DictTypeOption
	11, // 6: dict_type.Response.code:type_name -> google.protobuf.Int32Value
	1,  // 7: dict_type.DictTypeService.List:input_type -> dict_type.ListDictTypeRequest
	3,  // 8: dict_type.DictTypeService.Get:input_type -> dict_type.GetDictTypeRequest
	5,  // 9: dict_type.DictTypeService.Create:input_type -> dict_type.CreateDictTypeRequest
	6,  // 10: dict_type.DictTypeService.Update:input_type -> dict_type.UpdateDictTypeRequest
	7,  // 11: dict_type.DictTypeService.Delete:input_type -> dict_type.DeleteDictTypeRequest
	3,  // 12: dict_type.DictTypeService.RefreshCache:input_type -> dict_type.GetDictTypeRequest
	3,  // 13: dict_type.DictTypeService.OptionSelect:input_type -> dict_type.GetDictTypeRequest
	2,  // 14: dict_type.DictTypeService.List:output_type -> dict_type.ListDictTypeResponse
	4,  // 15: dict_type.DictTypeService.Get:output_type -> dict_type.GetDictTypeResponse
	10, // 16: dict_type.DictTypeService.Create:output_type -> dict_type.Response
	10, // 17: dict_type.DictTypeService.Update:output_type -> dict_type.Response
	10, // 18: dict_type.DictTypeService.Delete:output_type -> dict_type.Response
	10, // 19: dict_type.DictTypeService.RefreshCache:output_type -> dict_type.Response
	9,  // 20: dict_type.DictTypeService.OptionSelect:output_type -> dict_type.OptionSelectResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_zebra_passport_dict_type_dict_type_proto_init() }
func file_api_zebra_passport_dict_type_dict_type_proto_init() {
	if File_api_zebra_passport_dict_type_dict_type_proto != nil {
		return
	}
	file_api_zebra_passport_dict_type_dict_type_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zebra_passport_dict_type_dict_type_proto_rawDesc), len(file_api_zebra_passport_dict_type_dict_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zebra_passport_dict_type_dict_type_proto_goTypes,
		DependencyIndexes: file_api_zebra_passport_dict_type_dict_type_proto_depIdxs,
		MessageInfos:      file_api_zebra_passport_dict_type_dict_type_proto_msgTypes,
	}.Build()
	File_api_zebra_passport_dict_type_dict_type_proto = out.File
	file_api_zebra_passport_dict_type_dict_type_proto_goTypes = nil
	file_api_zebra_passport_dict_type_dict_type_proto_depIdxs = nil
}
