//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/zebra-passport/path/path.proto

package path

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// API路径信息
type Path struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PathName      string                 `protobuf:"bytes,2,opt,name=path_name,json=pathName,proto3" json:"path_name,omitempty"`
	PathUrl       string                 `protobuf:"bytes,3,opt,name=path_url,json=pathUrl,proto3" json:"path_url,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"` // GET, POST, PUT, DELETE
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"` // 0=禁用, 1=启用
	CreateTime    int64                  `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDeleted     int32                  `protobuf:"varint,9,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Path) Reset() {
	*x = Path{}
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Path) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Path) ProtoMessage() {}

func (x *Path) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Path.ProtoReflect.Descriptor instead.
func (*Path) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_path_path_proto_rawDescGZIP(), []int{0}
}

func (x *Path) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Path) GetPathName() string {
	if x != nil {
		return x.PathName
	}
	return ""
}

func (x *Path) GetPathUrl() string {
	if x != nil {
		return x.PathUrl
	}
	return ""
}

func (x *Path) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Path) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Path) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Path) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Path) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Path) GetIsDeleted() int32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

// 创建路径请求
type CreatePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PathName      string                 `protobuf:"bytes,1,opt,name=path_name,json=pathName,proto3" json:"path_name,omitempty"`
	PathUrl       string                 `protobuf:"bytes,2,opt,name=path_url,json=pathUrl,proto3" json:"path_url,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePathRequest) Reset() {
	*x = CreatePathRequest{}
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePathRequest) ProtoMessage() {}

func (x *CreatePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePathRequest.ProtoReflect.Descriptor instead.
func (*CreatePathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_path_path_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePathRequest) GetPathName() string {
	if x != nil {
		return x.PathName
	}
	return ""
}

func (x *CreatePathRequest) GetPathUrl() string {
	if x != nil {
		return x.PathUrl
	}
	return ""
}

func (x *CreatePathRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreatePathRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 更新路径请求
type UpdatePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PathName      string                 `protobuf:"bytes,2,opt,name=path_name,json=pathName,proto3" json:"path_name,omitempty"`
	PathUrl       string                 `protobuf:"bytes,3,opt,name=path_url,json=pathUrl,proto3" json:"path_url,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePathRequest) Reset() {
	*x = UpdatePathRequest{}
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePathRequest) ProtoMessage() {}

func (x *UpdatePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePathRequest.ProtoReflect.Descriptor instead.
func (*UpdatePathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_path_path_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePathRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdatePathRequest) GetPathName() string {
	if x != nil {
		return x.PathName
	}
	return ""
}

func (x *UpdatePathRequest) GetPathUrl() string {
	if x != nil {
		return x.PathUrl
	}
	return ""
}

func (x *UpdatePathRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *UpdatePathRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePathRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 删除路径请求
type DeletePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePathRequest) Reset() {
	*x = DeletePathRequest{}
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePathRequest) ProtoMessage() {}

func (x *DeletePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePathRequest.ProtoReflect.Descriptor instead.
func (*DeletePathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_path_path_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePathRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取路径请求
type GetPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPathRequest) Reset() {
	*x = GetPathRequest{}
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPathRequest) ProtoMessage() {}

func (x *GetPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPathRequest.ProtoReflect.Descriptor instead.
func (*GetPathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_path_path_proto_rawDescGZIP(), []int{4}
}

func (x *GetPathRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 获取路径响应
type GetPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *Path                  `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPathResponse) Reset() {
	*x = GetPathResponse{}
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPathResponse) ProtoMessage() {}

func (x *GetPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPathResponse.ProtoReflect.Descriptor instead.
func (*GetPathResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_path_path_proto_rawDescGZIP(), []int{5}
}

func (x *GetPathResponse) GetPath() *Path {
	if x != nil {
		return x.Path
	}
	return nil
}

// 列出路径请求
type ListPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	NameKeyword   string                 `protobuf:"bytes,3,opt,name=name_keyword,json=nameKeyword,proto3" json:"name_keyword,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPathRequest) Reset() {
	*x = ListPathRequest{}
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPathRequest) ProtoMessage() {}

func (x *ListPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPathRequest.ProtoReflect.Descriptor instead.
func (*ListPathRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_path_path_proto_rawDescGZIP(), []int{6}
}

func (x *ListPathRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPathRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListPathRequest) GetNameKeyword() string {
	if x != nil {
		return x.NameKeyword
	}
	return ""
}

func (x *ListPathRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ListPathRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 列出路径响应
type ListPathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []*Path                `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPathResponse) Reset() {
	*x = ListPathResponse{}
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPathResponse) ProtoMessage() {}

func (x *ListPathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_passport_path_path_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPathResponse.ProtoReflect.Descriptor instead.
func (*ListPathResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_passport_path_path_proto_rawDescGZIP(), []int{7}
}

func (x *ListPathResponse) GetPaths() []*Path {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *ListPathResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_zebra_passport_path_path_proto protoreflect.FileDescriptor

const file_api_zebra_passport_path_path_proto_rawDesc = "" +
	"\n" +
	"\"api/zebra-passport/path/path.proto\x12\x04path\"\x81\x02\n" +
	"\x04Path\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tpath_name\x18\x02 \x01(\tR\bpathName\x12\x19\n" +
	"\bpath_url\x18\x03 \x01(\tR\apathUrl\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\b \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\t \x01(\x05R\tisDeleted\"\x85\x01\n" +
	"\x11CreatePathRequest\x12\x1b\n" +
	"\tpath_name\x18\x01 \x01(\tR\bpathName\x12\x19\n" +
	"\bpath_url\x18\x02 \x01(\tR\apathUrl\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xad\x01\n" +
	"\x11UpdatePathRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tpath_name\x18\x02 \x01(\tR\bpathName\x12\x19\n" +
	"\bpath_url\x18\x03 \x01(\tR\apathUrl\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"#\n" +
	"\x11DeletePathRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\" \n" +
	"\x0eGetPathRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"1\n" +
	"\x0fGetPathResponse\x12\x1e\n" +
	"\x04path\x18\x01 \x01(\v2\n" +
	".path.PathR\x04path\"\x95\x01\n" +
	"\x0fListPathRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12!\n" +
	"\fname_keyword\x18\x03 \x01(\tR\vnameKeyword\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\"J\n" +
	"\x10ListPathResponse\x12 \n" +
	"\x05paths\x18\x01 \x03(\v2\n" +
	".path.PathR\x05paths\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\x85\x02\n" +
	"\vPathService\x12-\n" +
	"\x06Create\x12\x17.path.CreatePathRequest\x1a\n" +
	".path.Path\x12-\n" +
	"\x06Update\x12\x17.path.UpdatePathRequest\x1a\n" +
	".path.Path\x12-\n" +
	"\x06Delete\x12\x17.path.DeletePathRequest\x1a\n" +
	".path.Path\x122\n" +
	"\x03Get\x12\x14.path.GetPathRequest\x1a\x15.path.GetPathResponse\x125\n" +
	"\x04List\x12\x15.path.ListPathRequest\x1a\x16.path.ListPathResponseBCZA./github.com/21bigticket/zebra-proto/api/zebra-passport/path;pathb\x06proto3"

var (
	file_api_zebra_passport_path_path_proto_rawDescOnce sync.Once
	file_api_zebra_passport_path_path_proto_rawDescData []byte
)

func file_api_zebra_passport_path_path_proto_rawDescGZIP() []byte {
	file_api_zebra_passport_path_path_proto_rawDescOnce.Do(func() {
		file_api_zebra_passport_path_path_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zebra_passport_path_path_proto_rawDesc), len(file_api_zebra_passport_path_path_proto_rawDesc)))
	})
	return file_api_zebra_passport_path_path_proto_rawDescData
}

var file_api_zebra_passport_path_path_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_zebra_passport_path_path_proto_goTypes = []any{
	(*Path)(nil),              // 0: path.Path
	(*CreatePathRequest)(nil), // 1: path.CreatePathRequest
	(*UpdatePathRequest)(nil), // 2: path.UpdatePathRequest
	(*DeletePathRequest)(nil), // 3: path.DeletePathRequest
	(*GetPathRequest)(nil),    // 4: path.GetPathRequest
	(*GetPathResponse)(nil),   // 5: path.GetPathResponse
	(*ListPathRequest)(nil),   // 6: path.ListPathRequest
	(*ListPathResponse)(nil),  // 7: path.ListPathResponse
}
var file_api_zebra_passport_path_path_proto_depIdxs = []int32{
	0, // 0: path.GetPathResponse.path:type_name -> path.Path
	0, // 1: path.ListPathResponse.paths:type_name -> path.Path
	1, // 2: path.PathService.Create:input_type -> path.CreatePathRequest
	2, // 3: path.PathService.Update:input_type -> path.UpdatePathRequest
	3, // 4: path.PathService.Delete:input_type -> path.DeletePathRequest
	4, // 5: path.PathService.Get:input_type -> path.GetPathRequest
	6, // 6: path.PathService.List:input_type -> path.ListPathRequest
	0, // 7: path.PathService.Create:output_type -> path.Path
	0, // 8: path.PathService.Update:output_type -> path.Path
	0, // 9: path.PathService.Delete:output_type -> path.Path
	5, // 10: path.PathService.Get:output_type -> path.GetPathResponse
	7, // 11: path.PathService.List:output_type -> path.ListPathResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_zebra_passport_path_path_proto_init() }
func file_api_zebra_passport_path_path_proto_init() {
	if File_api_zebra_passport_path_path_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zebra_passport_path_path_proto_rawDesc), len(file_api_zebra_passport_path_path_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zebra_passport_path_path_proto_goTypes,
		DependencyIndexes: file_api_zebra_passport_path_path_proto_depIdxs,
		MessageInfos:      file_api_zebra_passport_path_path_proto_msgTypes,
	}.Build()
	File_api_zebra_passport_path_path_proto = out.File
	file_api_zebra_passport_path_path_proto_goTypes = nil
	file_api_zebra_passport_path_path_proto_depIdxs = nil
}
