//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/zebra-order/after_sales/after_sales.proto

package after_sales

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 售后单
type AfterSales struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SalesId       int64                  `protobuf:"varint,1,opt,name=sales_id,json=salesId,proto3" json:"sales_id,omitempty"`
	SalesNo       string                 `protobuf:"bytes,2,opt,name=sales_no,json=salesNo,proto3" json:"sales_no,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SalesType     int32                  `protobuf:"varint,5,opt,name=sales_type,json=salesType,proto3" json:"sales_type,omitempty"`          // 1=退款, 2=退货, 3=换货
	SalesReason   int32                  `protobuf:"varint,6,opt,name=sales_reason,json=salesReason,proto3" json:"sales_reason,omitempty"`    // 1=不想要了, 2=商品质量问题, 3=商品错发漏发, 4=其他
	SalesDesc     string                 `protobuf:"bytes,7,opt,name=sales_desc,json=salesDesc,proto3" json:"sales_desc,omitempty"`           // 售后说明
	RefundAmount  int64                  `protobuf:"varint,8,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"` // 退款金额（分）
	SalesStatus   int32                  `protobuf:"varint,9,opt,name=sales_status,json=salesStatus,proto3" json:"sales_status,omitempty"`    // 0=待审核, 1=审核通过, 2=审核拒绝, 3=退款中, 4=退款完成, 5=已关闭
	AuditRemark   string                 `protobuf:"bytes,10,opt,name=audit_remark,json=auditRemark,proto3" json:"audit_remark,omitempty"`    // 审核备注
	AuditTime     int64                  `protobuf:"varint,11,opt,name=audit_time,json=auditTime,proto3" json:"audit_time,omitempty"`
	RefundTime    int64                  `protobuf:"varint,12,opt,name=refund_time,json=refundTime,proto3" json:"refund_time,omitempty"`
	CreateTime    int64                  `protobuf:"varint,13,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,14,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDeleted     int32                  `protobuf:"varint,15,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterSales) Reset() {
	*x = AfterSales{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterSales) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterSales) ProtoMessage() {}

func (x *AfterSales) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterSales.ProtoReflect.Descriptor instead.
func (*AfterSales) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{0}
}

func (x *AfterSales) GetSalesId() int64 {
	if x != nil {
		return x.SalesId
	}
	return 0
}

func (x *AfterSales) GetSalesNo() string {
	if x != nil {
		return x.SalesNo
	}
	return ""
}

func (x *AfterSales) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *AfterSales) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AfterSales) GetSalesType() int32 {
	if x != nil {
		return x.SalesType
	}
	return 0
}

func (x *AfterSales) GetSalesReason() int32 {
	if x != nil {
		return x.SalesReason
	}
	return 0
}

func (x *AfterSales) GetSalesDesc() string {
	if x != nil {
		return x.SalesDesc
	}
	return ""
}

func (x *AfterSales) GetRefundAmount() int64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *AfterSales) GetSalesStatus() int32 {
	if x != nil {
		return x.SalesStatus
	}
	return 0
}

func (x *AfterSales) GetAuditRemark() string {
	if x != nil {
		return x.AuditRemark
	}
	return ""
}

func (x *AfterSales) GetAuditTime() int64 {
	if x != nil {
		return x.AuditTime
	}
	return 0
}

func (x *AfterSales) GetRefundTime() int64 {
	if x != nil {
		return x.RefundTime
	}
	return 0
}

func (x *AfterSales) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AfterSales) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *AfterSales) GetIsDeleted() int32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

// 售后单商品
type AfterSalesItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	SalesId       int64                  `protobuf:"varint,2,opt,name=sales_id,json=salesId,proto3" json:"sales_id,omitempty"`
	OrderItemId   int64                  `protobuf:"varint,3,opt,name=order_item_id,json=orderItemId,proto3" json:"order_item_id,omitempty"`
	SkuId         int64                  `protobuf:"varint,4,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SkuName       string                 `protobuf:"bytes,5,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	RefundAmount  int64                  `protobuf:"varint,7,opt,name=refund_amount,json=refundAmount,proto3" json:"refund_amount,omitempty"` // 退款金额（分）
	CreateTime    int64                  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	IsDeleted     int32                  `protobuf:"varint,10,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterSalesItem) Reset() {
	*x = AfterSalesItem{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterSalesItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterSalesItem) ProtoMessage() {}

func (x *AfterSalesItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterSalesItem.ProtoReflect.Descriptor instead.
func (*AfterSalesItem) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{1}
}

func (x *AfterSalesItem) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *AfterSalesItem) GetSalesId() int64 {
	if x != nil {
		return x.SalesId
	}
	return 0
}

func (x *AfterSalesItem) GetOrderItemId() int64 {
	if x != nil {
		return x.OrderItemId
	}
	return 0
}

func (x *AfterSalesItem) GetSkuId() int64 {
	if x != nil {
		return x.SkuId
	}
	return 0
}

func (x *AfterSalesItem) GetSkuName() string {
	if x != nil {
		return x.SkuName
	}
	return ""
}

func (x *AfterSalesItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AfterSalesItem) GetRefundAmount() int64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *AfterSalesItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *AfterSalesItem) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *AfterSalesItem) GetIsDeleted() int32 {
	if x != nil {
		return x.IsDeleted
	}
	return 0
}

// 创建售后单请求
type CreateAfterSalesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SalesType     int32                  `protobuf:"varint,3,opt,name=sales_type,json=salesType,proto3" json:"sales_type,omitempty"`
	SalesReason   int32                  `protobuf:"varint,4,opt,name=sales_reason,json=salesReason,proto3" json:"sales_reason,omitempty"`
	SalesDesc     string                 `protobuf:"bytes,5,opt,name=sales_desc,json=salesDesc,proto3" json:"sales_desc,omitempty"`
	OrderItemIds  []int64                `protobuf:"varint,6,rep,packed,name=order_item_ids,json=orderItemIds,proto3" json:"order_item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAfterSalesRequest) Reset() {
	*x = CreateAfterSalesRequest{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAfterSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAfterSalesRequest) ProtoMessage() {}

func (x *CreateAfterSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAfterSalesRequest.ProtoReflect.Descriptor instead.
func (*CreateAfterSalesRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAfterSalesRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateAfterSalesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateAfterSalesRequest) GetSalesType() int32 {
	if x != nil {
		return x.SalesType
	}
	return 0
}

func (x *CreateAfterSalesRequest) GetSalesReason() int32 {
	if x != nil {
		return x.SalesReason
	}
	return 0
}

func (x *CreateAfterSalesRequest) GetSalesDesc() string {
	if x != nil {
		return x.SalesDesc
	}
	return ""
}

func (x *CreateAfterSalesRequest) GetOrderItemIds() []int64 {
	if x != nil {
		return x.OrderItemIds
	}
	return nil
}

// 创建售后单响应
type CreateAfterSalesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterSales    *AfterSales            `protobuf:"bytes,1,opt,name=after_sales,json=afterSales,proto3" json:"after_sales,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAfterSalesResponse) Reset() {
	*x = CreateAfterSalesResponse{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAfterSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAfterSalesResponse) ProtoMessage() {}

func (x *CreateAfterSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAfterSalesResponse.ProtoReflect.Descriptor instead.
func (*CreateAfterSalesResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAfterSalesResponse) GetAfterSales() *AfterSales {
	if x != nil {
		return x.AfterSales
	}
	return nil
}

func (x *CreateAfterSalesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 审核售后单请求
type AuditAfterSalesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SalesNo       string                 `protobuf:"bytes,1,opt,name=sales_no,json=salesNo,proto3" json:"sales_no,omitempty"`
	AuditStatus   int32                  `protobuf:"varint,2,opt,name=audit_status,json=auditStatus,proto3" json:"audit_status,omitempty"` // 1=通过, 2=拒绝
	AuditRemark   string                 `protobuf:"bytes,3,opt,name=audit_remark,json=auditRemark,proto3" json:"audit_remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditAfterSalesRequest) Reset() {
	*x = AuditAfterSalesRequest{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditAfterSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditAfterSalesRequest) ProtoMessage() {}

func (x *AuditAfterSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditAfterSalesRequest.ProtoReflect.Descriptor instead.
func (*AuditAfterSalesRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{4}
}

func (x *AuditAfterSalesRequest) GetSalesNo() string {
	if x != nil {
		return x.SalesNo
	}
	return ""
}

func (x *AuditAfterSalesRequest) GetAuditStatus() int32 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *AuditAfterSalesRequest) GetAuditRemark() string {
	if x != nil {
		return x.AuditRemark
	}
	return ""
}

// 退款请求
type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SalesNo       string                 `protobuf:"bytes,1,opt,name=sales_no,json=salesNo,proto3" json:"sales_no,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{5}
}

func (x *RefundRequest) GetSalesNo() string {
	if x != nil {
		return x.SalesNo
	}
	return ""
}

// 查询售后单请求
type GetAfterSalesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Query:
	//
	//	*GetAfterSalesRequest_SalesNo
	//	*GetAfterSalesRequest_SalesId
	Query         isGetAfterSalesRequest_Query `protobuf_oneof:"query"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAfterSalesRequest) Reset() {
	*x = GetAfterSalesRequest{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAfterSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAfterSalesRequest) ProtoMessage() {}

func (x *GetAfterSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAfterSalesRequest.ProtoReflect.Descriptor instead.
func (*GetAfterSalesRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{6}
}

func (x *GetAfterSalesRequest) GetQuery() isGetAfterSalesRequest_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GetAfterSalesRequest) GetSalesNo() string {
	if x != nil {
		if x, ok := x.Query.(*GetAfterSalesRequest_SalesNo); ok {
			return x.SalesNo
		}
	}
	return ""
}

func (x *GetAfterSalesRequest) GetSalesId() int64 {
	if x != nil {
		if x, ok := x.Query.(*GetAfterSalesRequest_SalesId); ok {
			return x.SalesId
		}
	}
	return 0
}

type isGetAfterSalesRequest_Query interface {
	isGetAfterSalesRequest_Query()
}

type GetAfterSalesRequest_SalesNo struct {
	SalesNo string `protobuf:"bytes,1,opt,name=sales_no,json=salesNo,proto3,oneof"`
}

type GetAfterSalesRequest_SalesId struct {
	SalesId int64 `protobuf:"varint,2,opt,name=sales_id,json=salesId,proto3,oneof"`
}

func (*GetAfterSalesRequest_SalesNo) isGetAfterSalesRequest_Query() {}

func (*GetAfterSalesRequest_SalesId) isGetAfterSalesRequest_Query() {}

// 查询售后单响应
type GetAfterSalesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AfterSales    *AfterSales            `protobuf:"bytes,1,opt,name=after_sales,json=afterSales,proto3" json:"after_sales,omitempty"`
	Items         []*AfterSalesItem      `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAfterSalesResponse) Reset() {
	*x = GetAfterSalesResponse{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAfterSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAfterSalesResponse) ProtoMessage() {}

func (x *GetAfterSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAfterSalesResponse.ProtoReflect.Descriptor instead.
func (*GetAfterSalesResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{7}
}

func (x *GetAfterSalesResponse) GetAfterSales() *AfterSales {
	if x != nil {
		return x.AfterSales
	}
	return nil
}

func (x *GetAfterSalesResponse) GetItems() []*AfterSalesItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// 查询用户售后单列表请求
type GetUserAfterSalesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SalesStatus   int32                  `protobuf:"varint,2,opt,name=sales_status,json=salesStatus,proto3" json:"sales_status,omitempty"` // -1=全部
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAfterSalesRequest) Reset() {
	*x = GetUserAfterSalesRequest{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAfterSalesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAfterSalesRequest) ProtoMessage() {}

func (x *GetUserAfterSalesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAfterSalesRequest.ProtoReflect.Descriptor instead.
func (*GetUserAfterSalesRequest) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserAfterSalesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserAfterSalesRequest) GetSalesStatus() int32 {
	if x != nil {
		return x.SalesStatus
	}
	return 0
}

func (x *GetUserAfterSalesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserAfterSalesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 查询用户售后单列表响应
type GetUserAfterSalesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AfterSalesList []*AfterSales          `protobuf:"bytes,1,rep,name=after_sales_list,json=afterSalesList,proto3" json:"after_sales_list,omitempty"`
	Total          int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUserAfterSalesResponse) Reset() {
	*x = GetUserAfterSalesResponse{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAfterSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAfterSalesResponse) ProtoMessage() {}

func (x *GetUserAfterSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAfterSalesResponse.ProtoReflect.Descriptor instead.
func (*GetUserAfterSalesResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserAfterSalesResponse) GetAfterSalesList() []*AfterSales {
	if x != nil {
		return x.AfterSalesList
	}
	return nil
}

func (x *GetUserAfterSalesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 通用响应
type AfterSalesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AfterSales    *AfterSales            `protobuf:"bytes,3,opt,name=after_sales,json=afterSales,proto3" json:"after_sales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterSalesResponse) Reset() {
	*x = AfterSalesResponse{}
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterSalesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterSalesResponse) ProtoMessage() {}

func (x *AfterSalesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_zebra_order_after_sales_after_sales_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterSalesResponse.ProtoReflect.Descriptor instead.
func (*AfterSalesResponse) Descriptor() ([]byte, []int) {
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP(), []int{10}
}

func (x *AfterSalesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AfterSalesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AfterSalesResponse) GetAfterSales() *AfterSales {
	if x != nil {
		return x.AfterSales
	}
	return nil
}

var File_api_zebra_order_after_sales_after_sales_proto protoreflect.FileDescriptor

const file_api_zebra_order_after_sales_after_sales_proto_rawDesc = "" +
	"\n" +
	"-api/zebra-order/after_sales/after_sales.proto\x12\vafter_sales\"\xe3\x03\n" +
	"\n" +
	"AfterSales\x12\x19\n" +
	"\bsales_id\x18\x01 \x01(\x03R\asalesId\x12\x19\n" +
	"\bsales_no\x18\x02 \x01(\tR\asalesNo\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"sales_type\x18\x05 \x01(\x05R\tsalesType\x12!\n" +
	"\fsales_reason\x18\x06 \x01(\x05R\vsalesReason\x12\x1d\n" +
	"\n" +
	"sales_desc\x18\a \x01(\tR\tsalesDesc\x12#\n" +
	"\rrefund_amount\x18\b \x01(\x03R\frefundAmount\x12!\n" +
	"\fsales_status\x18\t \x01(\x05R\vsalesStatus\x12!\n" +
	"\faudit_remark\x18\n" +
	" \x01(\tR\vauditRemark\x12\x1d\n" +
	"\n" +
	"audit_time\x18\v \x01(\x03R\tauditTime\x12\x1f\n" +
	"\vrefund_time\x18\f \x01(\x03R\n" +
	"refundTime\x12\x1f\n" +
	"\vcreate_time\x18\r \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x0e \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x0f \x01(\x05R\tisDeleted\"\xbc\x02\n" +
	"\x0eAfterSalesItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x19\n" +
	"\bsales_id\x18\x02 \x01(\x03R\asalesId\x12\"\n" +
	"\rorder_item_id\x18\x03 \x01(\x03R\vorderItemId\x12\x15\n" +
	"\x06sku_id\x18\x04 \x01(\x03R\x05skuId\x12\x19\n" +
	"\bsku_name\x18\x05 \x01(\tR\askuName\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12#\n" +
	"\rrefund_amount\x18\a \x01(\x03R\frefundAmount\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\t \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\n" +
	" \x01(\x05R\tisDeleted\"\xd4\x01\n" +
	"\x17CreateAfterSalesRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"sales_type\x18\x03 \x01(\x05R\tsalesType\x12!\n" +
	"\fsales_reason\x18\x04 \x01(\x05R\vsalesReason\x12\x1d\n" +
	"\n" +
	"sales_desc\x18\x05 \x01(\tR\tsalesDesc\x12$\n" +
	"\x0eorder_item_ids\x18\x06 \x03(\x03R\forderItemIds\"n\n" +
	"\x18CreateAfterSalesResponse\x128\n" +
	"\vafter_sales\x18\x01 \x01(\v2\x17.after_sales.AfterSalesR\n" +
	"afterSales\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"y\n" +
	"\x16AuditAfterSalesRequest\x12\x19\n" +
	"\bsales_no\x18\x01 \x01(\tR\asalesNo\x12!\n" +
	"\faudit_status\x18\x02 \x01(\x05R\vauditStatus\x12!\n" +
	"\faudit_remark\x18\x03 \x01(\tR\vauditRemark\"*\n" +
	"\rRefundRequest\x12\x19\n" +
	"\bsales_no\x18\x01 \x01(\tR\asalesNo\"Y\n" +
	"\x14GetAfterSalesRequest\x12\x1b\n" +
	"\bsales_no\x18\x01 \x01(\tH\x00R\asalesNo\x12\x1b\n" +
	"\bsales_id\x18\x02 \x01(\x03H\x00R\asalesIdB\a\n" +
	"\x05query\"\x84\x01\n" +
	"\x15GetAfterSalesResponse\x128\n" +
	"\vafter_sales\x18\x01 \x01(\v2\x17.after_sales.AfterSalesR\n" +
	"afterSales\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.after_sales.AfterSalesItemR\x05items\"\x87\x01\n" +
	"\x18GetUserAfterSalesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fsales_status\x18\x02 \x01(\x05R\vsalesStatus\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"t\n" +
	"\x19GetUserAfterSalesResponse\x12A\n" +
	"\x10after_sales_list\x18\x01 \x03(\v2\x17.after_sales.AfterSalesR\x0eafterSalesList\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x82\x01\n" +
	"\x12AfterSalesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\vafter_sales\x18\x03 \x01(\v2\x17.after_sales.AfterSalesR\n" +
	"afterSales2\xd0\x03\n" +
	"\x11AfterSalesService\x12_\n" +
	"\x10CreateAfterSales\x12$.after_sales.CreateAfterSalesRequest\x1a%.after_sales.CreateAfterSalesResponse\x12W\n" +
	"\x0fAuditAfterSales\x12#.after_sales.AuditAfterSalesRequest\x1a\x1f.after_sales.AfterSalesResponse\x12E\n" +
	"\x06Refund\x12\x1a.after_sales.RefundRequest\x1a\x1f.after_sales.AfterSalesResponse\x12V\n" +
	"\rGetAfterSales\x12!.after_sales.GetAfterSalesRequest\x1a\".after_sales.GetAfterSalesResponse\x12b\n" +
	"\x11GetUserAfterSales\x12%.after_sales.GetUserAfterSalesRequest\x1a&.after_sales.GetUserAfterSalesResponseBNZL./github.com/21bigticket/zebra-proto/api/zebra-order/after_sales;after_salesb\x06proto3"

var (
	file_api_zebra_order_after_sales_after_sales_proto_rawDescOnce sync.Once
	file_api_zebra_order_after_sales_after_sales_proto_rawDescData []byte
)

func file_api_zebra_order_after_sales_after_sales_proto_rawDescGZIP() []byte {
	file_api_zebra_order_after_sales_after_sales_proto_rawDescOnce.Do(func() {
		file_api_zebra_order_after_sales_after_sales_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_zebra_order_after_sales_after_sales_proto_rawDesc), len(file_api_zebra_order_after_sales_after_sales_proto_rawDesc)))
	})
	return file_api_zebra_order_after_sales_after_sales_proto_rawDescData
}

var file_api_zebra_order_after_sales_after_sales_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_zebra_order_after_sales_after_sales_proto_goTypes = []any{
	(*AfterSales)(nil),                // 0: after_sales.AfterSales
	(*AfterSalesItem)(nil),            // 1: after_sales.AfterSalesItem
	(*CreateAfterSalesRequest)(nil),   // 2: after_sales.CreateAfterSalesRequest
	(*CreateAfterSalesResponse)(nil),  // 3: after_sales.CreateAfterSalesResponse
	(*AuditAfterSalesRequest)(nil),    // 4: after_sales.AuditAfterSalesRequest
	(*RefundRequest)(nil),             // 5: after_sales.RefundRequest
	(*GetAfterSalesRequest)(nil),      // 6: after_sales.GetAfterSalesRequest
	(*GetAfterSalesResponse)(nil),     // 7: after_sales.GetAfterSalesResponse
	(*GetUserAfterSalesRequest)(nil),  // 8: after_sales.GetUserAfterSalesRequest
	(*GetUserAfterSalesResponse)(nil), // 9: after_sales.GetUserAfterSalesResponse
	(*AfterSalesResponse)(nil),        // 10: after_sales.AfterSalesResponse
}
var file_api_zebra_order_after_sales_after_sales_proto_depIdxs = []int32{
	0,  // 0: after_sales.CreateAfterSalesResponse.after_sales:type_name -> after_sales.AfterSales
	0,  // 1: after_sales.GetAfterSalesResponse.after_sales:type_name -> after_sales.AfterSales
	1,  // 2: after_sales.GetAfterSalesResponse.items:type_name -> after_sales.AfterSalesItem
	0,  // 3: after_sales.GetUserAfterSalesResponse.after_sales_list:type_name -> after_sales.AfterSales
	0,  // 4: after_sales.AfterSalesResponse.after_sales:type_name -> after_sales.AfterSales
	2,  // 5: after_sales.AfterSalesService.CreateAfterSales:input_type -> after_sales.CreateAfterSalesRequest
	4,  // 6: after_sales.AfterSalesService.AuditAfterSales:input_type -> after_sales.AuditAfterSalesRequest
	5,  // 7: after_sales.AfterSalesService.Refund:input_type -> after_sales.RefundRequest
	6,  // 8: after_sales.AfterSalesService.GetAfterSales:input_type -> after_sales.GetAfterSalesRequest
	8,  // 9: after_sales.AfterSalesService.GetUserAfterSales:input_type -> after_sales.GetUserAfterSalesRequest
	3,  // 10: after_sales.AfterSalesService.CreateAfterSales:output_type -> after_sales.CreateAfterSalesResponse
	10, // 11: after_sales.AfterSalesService.AuditAfterSales:output_type -> after_sales.AfterSalesResponse
	10, // 12: after_sales.AfterSalesService.Refund:output_type -> after_sales.AfterSalesResponse
	7,  // 13: after_sales.AfterSalesService.GetAfterSales:output_type -> after_sales.GetAfterSalesResponse
	9,  // 14: after_sales.AfterSalesService.GetUserAfterSales:output_type -> after_sales.GetUserAfterSalesResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_zebra_order_after_sales_after_sales_proto_init() }
func file_api_zebra_order_after_sales_after_sales_proto_init() {
	if File_api_zebra_order_after_sales_after_sales_proto != nil {
		return
	}
	file_api_zebra_order_after_sales_after_sales_proto_msgTypes[6].OneofWrappers = []any{
		(*GetAfterSalesRequest_SalesNo)(nil),
		(*GetAfterSalesRequest_SalesId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_zebra_order_after_sales_after_sales_proto_rawDesc), len(file_api_zebra_order_after_sales_after_sales_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_zebra_order_after_sales_after_sales_proto_goTypes,
		DependencyIndexes: file_api_zebra_order_after_sales_after_sales_proto_depIdxs,
		MessageInfos:      file_api_zebra_order_after_sales_after_sales_proto_msgTypes,
	}.Build()
	File_api_zebra_order_after_sales_after_sales_proto = out.File
	file_api_zebra_order_after_sales_after_sales_proto_goTypes = nil
	file_api_zebra_order_after_sales_after_sales_proto_depIdxs = nil
}
